### ISSUE TITLE
Updating etc..

### ISSUE THREAD

**Issue by Lewdninja** [Lewdninja/liveme-pro-tools#1]
I might consider keeping on updating & fixing this script as time goes on if people are willing to donate. 
If people are interested in me actively fixing and updating the script let me know here. I would probably rewrite a lot of the code and the UI.

**Edit:** I'll just leave these here for now.
```
BTC: 3Kzb15U59LeMsvGoAZW1hsDYMXTVQoARmq
ETH: 0x593186F9b31C4761654B37d7965a189928Ae87DD
LTC: MGG4nfqmLGYaKQ5UAQJ8bNBnzQ3Ws8iNma
```
https://www.patreon.com/lewdninja

**Comment by ddpk** [comment]
Me too. Just have to see if more people catch on to your fix and see you'd be taking over things. Is there a redirect to the fix on the original pro tools page anywhere? I wonder how many wanting the fix still don't know about it

**Comment by starsaillor** [comment]
Maybe it's time to let everyone know then

**Comment by Grindteeth** [comment]
I'm willing to donate. But I doubt many people are even aware of you taking over.

**Comment by ddpk** [comment]
I feel like if you do take it over your link should also be shared on the original Liveme tools page because I was a few months late to knowing anything about Pro tools. Pretty sure I only just found out 3 days ago when the original stopped working.

**Comment by nubcaek11** [comment]
An automatic live capper from the bookmarks list (or some new list) would be amazing.  That, and some way to save all the m3u8 links from a user to a local file, and this thing would do it all.

**Comment by bubu23bubu23** [comment]
Lewdninja you say you add support for m3u8 etc.... when i download the tool it still the same tool how can i update it ..sorry for the stupid question

**Comment by Lewdninja** [comment]
I haven't uploaded the new setup files yet.

**Comment by ddpk** [comment]
@nubcaek11 I wouldn't want a live capper necessarily. But a list of all new replays caught in a queue of your bookmarks would be nice. I hate live capping, I'd only want to get the replays. It would be cool to have an auto updating list of recent replays with "X minutes ago" etc. Not categorized by user but by date and time (most recent) . Similar to the feature that's on liveme pro tools homepage but a little more advanced maybe with notifications or something? I wonder if any of this makes sense @Lewdninja I know this tool is mainly for browsing and not built for downloading or tracking replays but it has a lot of potential to be that

**Comment by ddpk** [comment]
Also, I'd go for Patreon tbh.

**Comment by ddpk** [comment]
@nubcaek11 Saving all m3u8 to a txt from a user would be so nice. Some kind of videoID-m3u8 format and txt name be the userID would be great,

**Comment by nubcaek11** [comment]
@ddpk I've only ever used a live capper for broadcasters who habitually delete everything right away, or broadcasters who are likely to get banned for...whatever reason.  I prefer replays too, but sometimes it's difficult or impossible.  I had a live capper that broke at the same time as everything else, but before that, it grabbed a couple broadcasts while I was away that otherwise would have been lost to the ether.  Still, a running list of all the m3u8s from bookmarks concatenated to a local file would be pretty useful.

**Comment by Lewdninja** [comment]
Since not a lot of people really care about the Patreon nor crypto addresses I will probably add some nonintrusive ads into the application with a option to disable them if you are a patron. **Closing this, but feel free to discuss this topic on Discord.**
