### ISSUE TITLE
no new update to the tool?

### ISSUE THREAD

**Issue by bubu23bubu23** [Lewdninja/liveme-pro-tools#101]
lolllll

**Comment by thedude1999** [comment]
seems like a weekly event anymore.

**Comment by GumiG** [comment]
what do u want added? its perfect for me till it breaks again.

**Comment by bubu23bubu23** [comment]
my friend firsdt of all thx for your work second many stuff not working as expect like:1: the follower and the follower friend in the settings in the program when yopu set the mark it not work it hide always followers that dont have replay2:the program download reply very slow all the third party apps download lot faster3:we need many new stuff to add to the program that will work good like: search by country its very importent 2:ther hash tag not seartch good i always get only few founds it cant be from thousend of reply i get only few when i using hashtag4:we need back button so if you search for user name and you find a user with reply  and you scroll 50 users to get to him and you wach his replay you cany go back to your search you need to search again and  scroll again it weill be nice for back button


now plz im sure you can !!!!! i will pay you privatlly nice amount if youll do it silncelly and make a way to tell how to find a user deleted replay cause i know myself little programiong and i made record once or twice and i see trhat i delete my replay but still the replay say in the databace even after long time you have to get a special code that i try to get and couldnt i  will send you money if youll tell me how you dont need to publish it cause its iillegal but you can sale private or tell me how to find and ill send you paypal money ill give you 100$ for this you thionk about it how to get from user name or from video id the code to get the replay orrrr !!! from user name to get all the replay the user had and have even with thouse that he was deleted i will pay for this for private use (if you want to make money this is my offer think about it and let me know  plz ) thx for the stuff wait for your replay !!!!    On Wednesday, May 30, 2018, 3:53:36 PM GMT+3, GumiG <notifications@github.com> wrote:  
 
 
what do u want added? its perfect for me till it breaks again.

**Comment by ddpk** [comment]
What the fuck did I just read

**Comment by Xqqz** [comment]
@ddpk  , LOL
it was difficult... but i think he wants #96  #94 #99 

plus the ability to get link for a Broadcasters entire replays, even ones deleted by broadcaster/Liveme  , etc.

**Comment by ddpk** [comment]
@Xqqz That last one seems pretty impossible to me but I understand you were just reiterating what he was saying

**Comment by bubu23bubu23** [comment]
i know my friend that was a joke lolllll 

    On Wednesday, June 6, 2018, 6:00:48 PM GMT+3, Xqqz <notifications@github.com> wrote:  
 
 
@ddpk , yes, the last one was impossible, only way that's possible is to h@ck Liveme servers.. he wanted that, or a miracle ..
LOL
