### ISSUE TITLE
Javascript error at LMPT launch on Mac

### ISSUE THREAD

**Issue by XxhollandxX** [Lewdninja/liveme-pro-tools#109]
Apologies for asking but any thoughts on this?

Uncaught Exception:
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /Applications/LiveMe Pro Tools.app/Contents/Resources/app.asar/datamanager.js:69:37
    at tryToString (fs.js:513:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:501:12)

**Comment by Xqqz** [comment]
@XxhollandxX   possible UNFINISHED DOWNLOADS in the que.....

* I dont have a MAC but experience those errors on Windows PC when i have unfinished downloads and i restart the LMPT app.

**Comment by XxhollandxX** [comment]
Thx Xqqz - I don't have any downloads at all. I never downloaded anything because I cannot authenticate either. I told that perhaps the JSON message had something to do with the authentication error.

**Comment by Xqqz** [comment]
@XxhollandxX  a few hours ago LMPT would NOT authenticate no matter how many times I restarted it, 
so, I powered off the computer , and then turn it back on,
start up LMPT and everything worked fine after that.
Windows 7x64 Ultimate

**Comment by thedude1999** [comment]
Same issue on windows now. Uninstalled and reinstalled.

**Comment by thedude1999** [comment]
So no solutions to this?

**Comment by Lewdninja** [comment]
Your ``profiles.json`` file is corrupt.
