### ISSUE TITLE
Failed to authenticate with live.me servers (invalid credentials?)

### ISSUE THREAD

**Issue by asdfghjiuy** [Lewdninja/liveme-pro-tools#110]
anyone else getting this while entering login info on LMPT? I've tried to log in with 3 different accounts, i know the passwords and emails were correct and the accounts are functioning how they should on the live.me app. Any help would be great, thanks.

**Comment by thedude1999** [comment]
just keep trying. it does that sometimes

**Comment by WoobWoobWoob** [comment]
I've had this too. Started the other night. I've tried three separate accounts (can login to liveme.com using all three e-mail/password combinations). But each time I try it with LMPT it says I am not authenticated and to enter my login details under settings.

I've deleted the files in the windows appdata folder, uninstalled and reinstalled. I've disabled my firewall. But it will keep telling me I'm not authenticated.

Also, I don't know if this has something to do with it, but at the bottom of the main screen, there's an empty bar and it says "Bookmarks are now being scanned for new replays..." The message does not go away. And I do not have any accounts bookmarked.

**Comment by Xqqz** [comment]
@WoobWoobWoob @asdfghjiuy  @Joshiboy99  , I had the same issues
I restarted my computer and the problem went away.

**Comment by robwas** [comment]
Same issue, haven't tried restarting my computer yet.  On the bottom is says "1 accounts found so far, scroll down to load more."

**Comment by robwas** [comment]
So I didn't reboot but I just kept restarting the app and now it works, took about 7 tries then it authenticated.

**Comment by artorawley** [comment]
Restarted the app and it's no longer authenticating. Tried three different accounts, opened & closed app, and deleted settings.json in AppData and it still won't authenticate.

**Comment by lifesuckz69** [comment]
Today i also got the issue that it's not authenticating anymore. didn'T change anything and the account is still valid.

**Comment by scozz76** [comment]
I just had this issue. To solve this I changed my VPN location.
