### ISSUE TITLE
Support the LMPT developer - Become a patreon

### ISSUE THREAD

**Issue by Xqqz** [Lewdninja/liveme-pro-tools#111]
https://www.patreon.com/lewdninja

Get stuff and information  faster about the BEST LIVE.ME APP around
Get access to  @Lewdninja  community & posts.

Patrons benefit(s): 

Early Critical Fixes
$5 or more per month
You'll receive early critical fixes to the app 2-3 days before anyone else.

Early Updates and Improvements
$10 or more per month
You'll receive early updates and improvements made to the app 7 days before anyone else.

SuperUser
$25 or more per month
Previous rewards, plus you'll be able to vote on upcoming features/fixes/updates etc..

* It's well worth it, to help keep LMPT / Liveme-api development alive.

https://www.patreon.com/lewdninja

**Comment by thedude1999** [comment]
Is he ever coming back? I know he said he'd be back in July...

**Comment by Xqqz** [comment]
hope so

**Comment by Lewdninja** [comment]
Yes, I'm making a Patreon post today stating what I'm currently working on.
