### ISSUE TITLE
cant login

### ISSUE THREAD

**Issue by tofifi1** [Lewdninja/liveme-pro-tools#112]
suddenly i cant log in 
i did everything write here but it keep say
"you are not authenticated "

what to do i did every thing people say here
update : i even made new gmail  but when i put it in the log in area of the toll it say error
and live me didnt send me activasion mail

**Comment by Johnlourence** [comment]
I have the same issue. Anybody else have this problem??

**Comment by calluch** [comment]
same issue here

**Comment by Xqqz** [comment]
@Johnlourence @calluch @tofifi1 

First,  Log out of Liveme APP on ALL your devices
then
1: Close LMPT
2: Go in your Windows folder here
C:\Users\YOURUSERNAMEHERE\AppData\Roaming\liveme-pro-tools
3: and delete the contents in the CACHE and GPUcache folder.
4: Restart your computer.

5: Log into LMPT with  your email

6: Use a DIFFERENT email/account to log into Liveme APP

* You should basically have an email/account JUST FOR LMPT use ONLY.

**Comment by calluch** [comment]
thanks but still no go   i created a new gmail just for LMPT

**Comment by tp9ine** [comment]
@calluch I just want to make sure, you signed up on LiveMe with the email option (not the Google Plus / Gmail) option, correct?

**Comment by calluch** [comment]
yes.....correct...i signed up with the email option on liveme

**Comment by calluch** [comment]
i just created a brand new email account on yahoo and created an account on liveme and it worked fine.....finally.....thanks all for your help....back in business !!!

**Comment by silenteyes705** [comment]
i just did the same but again  you are not authenticated i just sign up with my yahoo mail befor i was signed up with my mobile number  now waht should i do

**Comment by silenteyes705** [comment]
?

**Comment by Xqqz** [comment]
@silenteyes705  when you signed up with YAHOO MAIL
did you click the link you received from Liveme.com in your yahoo-mail  to VERIFY/AUTHENTICATE/ACTIVATE the account ?
