### ISSUE TITLE
Player needs updating ?

### ISSUE THREAD

**Issue by thegeezer9999** [Lewdninja/liveme-pro-tools#117]
Many of the broadcasts now go into a loop (spinning circle) and cannot recover. Sometimes skipping to a further point on the video works (but not always). The video plays fine if downloaded and MPC used (VLC has same problem - just does not play), so looks like a problem with the encoder/decoder recovering ability when it hits a glitch in the track.
Same video plays fine on phone app.
Seems to happen increasingly often now, I have HS broadband so pretty sure not a connectivity issue.

Thanks for investigating

**Comment by happykeppi** [comment]
I believe it's not necessarily a software related problem. Sometimes the videos are just badly decoded due to connectivity issues by the broadcaster.

**Comment by Xqqz** [comment]
You are correct @happykeppi

**Comment by Lewdninja** [comment]
If it's related to the HLS addon the player uses then it needs to be fixed here: https://github.com/videojs/videojs-contrib-hls

**Comment by thegeezer9999** [comment]
OK I think LM must have implemented a new feature to allow users to expire bcs after 24 hours since most of the "spinning" ones are marked as "expired" on the app (note you can, in most cases still download/play them). This is crap since for many users, they either have all expired or a large portion now. So LM manages to f*&^% things up again !!

**Comment by tp9ine** [comment]
@thegeezer9999 I don't think this has anything to do with your original question. I created a broadcast and there is no such option to expire broadcasts, but maybe you have to be a high enough b.level. By the way, I've seen broadcasts expire immediately right after appearing/processing.

As for the spinning circle loop, I think it simply has to do with server/connectivity issues. I notice if you spam click a few times on the time bar somewhere, it will actually recover most of the time. Also, might be a reason why downloads in LMPT stop abruptly sometimes.

**Comment by thegeezer9999** [comment]
Glad it is not just me :-)
Seriously, they have a great product here but it is being screwed up by mismanagement,
This can be closed Lewd.
