### ISSUE TITLE
Pleasssse... place a confirmation dialog after hitting the close "x" button

### ISSUE THREAD

**Issue by blakrovv** [Lewdninja/liveme-pro-tools#118]
It's been quite a few times I hit it accidentally and then everything goes to waste.

**Comment by tp9ine** [comment]
Yes please. I don't know how many times I've closed the app by accident and lose my place and downloads. Except I use keyboard controls mostly. I press ctrl+w to close a "following/followers" window but sometimes I get antsy and press it twice and the main window gets closed. So annoying.
