### ISSUE TITLE
authentication issues

### ISSUE THREAD

**Issue by kongiscranky** [Lewdninja/liveme-pro-tools#121]
Started having authentication issues yesterday on Mac. Tried a second Mac and got same issues, created a new account and tried on both again but continued to have issues. Did fresh install on one mac, same issue. Installed on PC and still having issues with both accounts. Any ideas? Anyone else having this issue across the board?

**Comment by tng18** [comment]
Yup same thing for me on Windows; 1.1.9 authentication issues, 1.1.8 works fine

**Comment by vanimox** [comment]
I can confirm, downgrading to 1.1.8 fixes the authentication issues.

**Comment by Smiley0227** [comment]
Confirming as well. Been having authentication issue since yesterday. Downgrading to 1.1.8 fixes the issue.

**Comment by barakaka** [comment]
Pretty sure it's ip related.  Have to change your ip.  Changing anything else has no effect.

**Comment by robwas** [comment]
Same issue, about to try 1.1.8 myself.  Did you guys have to remove 1.1.9 or just install over top of it?

**Comment by robwas** [comment]
Installed without removing 1.1.9 and it just worked as others have said, hats off to whoever tried this, I would have never thought of installed a legacy version.  Wonder what gives?

**Comment by Lewdninja** [comment]
Version 1.1.9 didn't change anything related to auth.

**Comment by Lewdninja** [comment]
The update changed from web login method to the login the actual app uses. There were problems with web method, therefore the change.

Also the app is working fine for me, but I am running the dev version which has captcha check implemented (sort of).

**Comment by tacosteven** [comment]
is there anyway that 1.1.8 could be released for mac format?

**Comment by Smiley0227** [comment]
> Also the app is working fine for me, but I am running the dev version which has captcha check implemented (sort of).

Perhaps that's the issue then, the captcha. All of a sudden, I have to complete a captcha everytime I login on the website. Plus, the captcha doesn't work on Firefox.

BTW, I like what was done on the player in the latest version. It's great to be able to rotate the video.

**Comment by kongiscranky** [comment]
Also, just to confirm I tried 1.1.7 for Mac and it didn't work either. I might not have done a complete clear of 1.1.9's system files though so i'll try again

**Comment by tp9ine** [comment]
@Lewdninja  is there a reason why they are using captcha. are they trying to block ppl from downloading? or other reason.

**Comment by demondecon** [comment]
The captcha is definitely the issue.  When using 1.1.8 on a mac (source code and npm)  I'm still getting failed to authenticate with the following popping up on the terminal directly after inputting my email and password.

IS_EXIST RESPONSE:  { ret: 12006, data: { captcha: '' } }

This makes me assume that the login is expecting a captcha which is not being provided.

**Comment by Lewdninja** [comment]
@tp9ine They are using captcha to stop automated logins like this app is using (probably, don't quote me on this).

@demondecon Actually no, the captcha requirement comes from the next request that's not logged in the console. The exist response always returns an empty captcha object. If it has an URL, then the captcha is required.

**Comment by tp9ine** [comment]
@Lewdninja So they are using captcha to stop automated logins, so why are they requiring logins in the first place? That's what I'm wondering.

**Comment by str4p** [comment]
I seem to be getting this error when attempting login:

{"ret":12101,"msg":"To much request","data":{"captcha":""}}

I've also tried creating a new account / changing IPs

anyone else having this problem?

**Comment by ginnygin** [comment]
Does anyone know how to make a .dmg for the previous version of the program.  I am lost without the program.

**Comment by latenate16** [comment]
@ginnygin.  Not a DMG solution but it works - found it in another thread.

<img width="670" alt="screen shot 2018-07-22 at 7 41 58 am" src="https://user-images.githubusercontent.com/38624939/43352888-51148fcc-91f9-11e8-9e9c-fa0c18aecd29.png">

**Comment by ginnygin** [comment]
@latenate16 any suggestions. I tried installed and still asks for authentification.  Any help would be great.  Thanks for the advice on the one above.

**Comment by Smiley0227** [comment]
@ginnygin Not sure if this is what you're looking for, but it was the first google result.

https://gist.github.com/jadeatucker/5382343

**Comment by XxhollandxX** [comment]
THX @barakaka these instructions work perfectly, however, still cannot get into LMPT 1.18 on a MA. Any other ideas? Anybody? Thank you for responding.
