### ISSUE TITLE
Watch REPLAYS at 2X speed .. possible ?

### ISSUE THREAD

**Issue by Xqqz** [Lewdninja/liveme-pro-tools#124]
Watching REPLAYS here : <removed by lewd>
You can actually increase the PLAYING speed to 1.5X or 2X speed,
 also can SLOW DOWN viewing to 0.7X or 0.5X  

Is that possible to implement into LMPT 2.0 ?

**Comment by smagdan** [comment]
MPC-HC

**Comment by smagdan** [comment]
Me neither.. you can do it for streaming too
