### ISSUE TITLE
Does Liveme ban IPs for using this app?

### ISSUE THREAD

**Issue by artorawley** [Lewdninja/liveme-pro-tools#127]
I've encountered a weird thing where I can't log into any of my accounts via a specific IP for some reason. On the Liveme app I get "Connection Error" when I try to log in, and in LMPT I get a "User No Longer Exists" error for every account I view. Oddly enough, I can use the exact same accounts just fine on a different IP, so it's not like they banned any of my accounts (I even checked to make sure, and they're still up). Has this happened to anyone else?

**Comment by bubu23bubu23** [comment]
yep!!!! you need to change the ip if its not static or get vpn ,sorry

**Comment by tp9ine** [comment]
Did you give them a reason that might have caused it? Like queueing up tons of downloads that would take all day and night to complete?

**Comment by artorawley** [comment]
Nope. I've used the actual app and this app simultaneously before, albeit on separate accounts, but I've seen broadcasts where people have broadcasted on the same wifi with their friends at the same time so I don't think that would do it. Also, like I said the actual accounts still work fine, it's just from a single IP that they don't connect so it doesn't seem like the accounts got flagged.

**Comment by kivoxusubi** [comment]
i feel like when you have a lot of bookmarks and you update them all at once and it sends say 300 requests in like 10 seconds, that might be something that could trigger it.
