### ISSUE TITLE
New replays of bookmarked accounts do not show

### ISSUE THREAD

**Issue by Casemiro555** [Lewdninja/liveme-pro-tools#128]
I tried a fresh install, new bookmarks, just a few active accounts. The message "bookmarks are now being scanned for new replays..." stays on the lower right corner and never shows the updated accounts. Same thing on the bookmarks tab. I tried waiting 30 mn, same thing.

**Comment by Xqqz** [comment]
@Casemiro555  What version of LMPT are you using ?

**Comment by Casemiro555** [comment]
I'm using the last version (1.1.9) and yes, the bookmarks have streams, and yes, i am logged in as I can watch them. It's just that the program does not tell me whenever a recent replay is available in one of the bookmarked accounts. It used to work with previous versions, it just stopped working.

**Comment by Xqqz** [comment]
@Casemiro555  ,  I wasn't aware that 1.1.9 was working..
I'll install and test

**Comment by Xqqz** [comment]
@Casemiro555   i tested 1.1.9 and its still not working

Are you aware of #121   ?

**Comment by Casemiro555** [comment]
@Xqqz well I checked this and I have no authentication issues afaik. I can watch any replay, it's only the "warn me on new replays" feature that does not work. And also the updating of the bookmarks (ie the number of replays/fan/following never updates). 
I also tried 1.1.8, same thing. I will try with a new account...

**Comment by thegeezer9999** [comment]
What happens if you select your favourites, display on right hand side in separate window, then hit the "eye" - does that then highlight all the non-viewed in green ? This works fine for me on 1.19

**Comment by Casemiro555** [comment]
@thegeezer9999 it does not work for me on 1.1.9. Will create a new login to check.

**Comment by Casemiro555** [comment]
Is there a way to check the logs or have a console access ?

**Comment by Casemiro555** [comment]
Well that was an issue with my login. Created a new one, and it works. So it seems some login don't create explicit authentication issues but still prevents bookmarks from refreshing...
