### ISSUE TITLE
Followings Not Showing

### ISSUE THREAD

**Issue by Mikerowdy** [Lewdninja/liveme-pro-tools#129]
Authenticated 2 accounts, When seeing who users are following, box won't display on desktop. it shows a tab being open but won't show on screen. Fans and replays work fine. Was working correctly until after I verified and its a brand new account. Has this happened to anyone else?

**Comment by Mikerowdy** [comment]
I attempted a reinstall and switched back to 1.1.8. I went through the files, deleted everything, uninstalled, reinstalled, no change.
the bottom icon opens and a preview loads showing "followings," however it does not display on the screen. Again, works fine if an account is not authenticated but of course then you can't see replays

**Comment by Xqqz** [comment]
@Mikerowdy  see this post #130  , maybe it can help.
