### ISSUE TITLE
Bug - v1.xx Follows 

### ISSUE THREAD

**Issue by thegeezer9999** [Lewdninja/liveme-pro-tools#13]
To recreate
1. Add a username like
2. Select Following
3. Open one of the Following
4. Now input a completely different username like
5. Hit Following
6. Does not show the Following of the new entry, shows the Following of previous entry
Only work round is to close/re-open application

W10x64

**Comment by thegeezer9999** [comment]
Agree the issue occurred with earlier versions, but it is till a bug. I will try the way you suggest though :-)

**Comment by thegeezer9999** [comment]
@starsailor This worked for me with a slight variation, I had to first OPEN their replays, then select the follows. Thanks for the advice - this can be closed (unless there is a simple fix ?)

**Comment by Lewdninja** [comment]
Should be fixed in 1.1.9
