### ISSUE TITLE
FIXED

### ISSUE THREAD

**Issue by Xqqz** [Lewdninja/liveme-pro-tools#130]
"All" the "followings" of a user is "not showing" up in LMPT Only "some" , sometimes.

How to create  this issue:
1: Open BOOKMARK... find a user that's not following a LOT of people, easier for this testing.

2: Note the TOTAL people that user IS FOLLOWING, now, Click the "Following" button of that user
Result: only SOME of the  followings  shows:

My Liveme account i'm following 20 people, all active, when i go on LMPT it shows that i'm following 20 .. but when i click my "Following" on LMPT .. only 6 shows up on the pop-up screen.
( even tho at the bottom of the screen the message states " Showing 20 of 20 accounts" )

When i click the "FANS" button ,  all 45 users thats FANS of me in the APP SHOWS, as it should ..... 

Problem is ONLY on the "FOLLOWING" side

* when i FIRST click the "Following" button, the screen FLASHED and showed all-20 Followings for maybe half-of-a-second , then shows ONLY 6 

example

![bandicam 2018-08-19 02-38-19-902](https://user-images.githubusercontent.com/38635388/44306303-a32f4100-a359-11e8-815d-716064e7ae65.jpg)

**Comment by tp9ine** [comment]
I'm not sure if I quite understood everything you said but I think it's because broadcasters with 0 replays is filtered out.

**Comment by Xqqz** [comment]
Nope..my settings has its UN-checked

![bandicam 2018-08-19 00-28-35-964](https://user-images.githubusercontent.com/38635388/44305503-e2a06200-a346-11e8-8a46-11842e12516a.jpg)

**Comment by Xqqz** [comment]
@tp9ine  , your answer propmpted me to investigate further.
Thanks to you.. i decided to check the "settings" file in 
and found that even tho i have  my settings in the APP   to allow ZERO REPLAYS Followings, the SETTINGS file was NOT SAVING IT

I went into "C:\Users\ADMIN\AppData\Roaming\liveme-pro-tools"
I manually changed the SETTINGS file:
From
"hide_zeroreplay_fans":false,"hide_zeroreplay_followings":true}
to
"hide_zeroreplay_fans":false,"hide_zeroreplay_followings":false}

SAVED IT, restarted LMPT..... and now all seems to be WELL .

Thanks

**Comment by ginnygin** [comment]
Xqqz could you help me with this problem.  All following show up for a second and then most disappear.  Any chance you can explain how to do that fix you were talking about earlier.  Cant find the location of C:\Users\ADMIN\AppData\Roaming\liveme-pro-tools
