### ISSUE TITLE
Install LMPT 1.9 no visual start

### ISSUE THREAD

**Issue by SteveKajak** [Lewdninja/liveme-pro-tools#136]
Hello, I installed LMPT 1.9 on my 2nd computer (Windows10) today. After the installation I started the program. Unfortunately the program does not open visually but it is open in the Task Manager. What do I have to consider to see the program as well? I have turned off the installation antivirus and firewall. Nevertheless, it does not open properly. Also, the start with admin rights has brought nothing.
Many thanks for the help.

**Comment by Xqqz** [comment]
Use LMPT 1.1.8 

or go here : https://notabug.org/thecoder1975/liveme-pro-tools

**Comment by SteveKajak** [comment]
LMPT 1.1.8  also not working.
I need a install Manual for the new LMPT 1.2 Tool or a Installer Tool.
