### ISSUE TITLE
Immediate download error. (Fixed!)

### ISSUE THREAD

**Issue by greatsalmonrun** [Lewdninja/liveme-pro-tools#14]
Hello, the newest version is giving me an immediate download error. It isn't the queued bug, it simply throws an error.

Already attempted a complete uninstall and tried deleting all of the appdata to no avail.

**Comment by smagdan** [comment]
install ffmpeg

**Comment by Mush-r00m** [comment]
@greatsalmonrun  You need to install ffmpeg into  C:\Windows folder. There are plenty of guides online.

**Comment by greatsalmonrun** [comment]
Already did it @Mush-r00m @smagdan

**Comment by stonedmonkey** [comment]
same thing for mac and we dont have c:\Windows any ideas?

**Comment by Lewdninja** [comment]
It needs to be available in the PATH settings. One way you can test this is to open a terminal/cmd prompt and type in ``ffmpeg -version`` and if there's an output like ``ffmpeg version 3.4....`` then it should be fine.

If it's not, then there should be plenty of tutorials on how do add ffmpeg to PATH.
