### ISSUE TITLE
Won't let me authenticate

### ISSUE THREAD

**Issue by bigugly3** [Lewdninja/liveme-pro-tools#141]
It won't let me authenticate.  It saved some old login and I put in the new login and it doesn't change anything.  I go out of it and come back in and it has the old login already in there and won't authenticate.  Also all my old bookmarks are gone except about 5 that were the first ones I bookmarked long ago.

**Comment by Xqqz** [comment]
What version of LMPT are you using ?

**Comment by pinkystinky** [comment]
Hey--I'm having the same issue. I Can't speak for bigugly3 but i've tried versions 1.19, 1.18 and 1.16 and i get the same issue. I've also used old accounts and created new accounts but get the same issue.

**Comment by Xqqz** [comment]
@pinkystinky , uninstall LMPT
install LewdNinjas version 1.1.8  from https://github.com/Lewdninja/liveme-pro-tools/releases , or 
TheCoders 1.209.20180918 version from https://notabug.org/thecoder1975/liveme-pro-tools/releases 

create an account using EMAIL just to use on LMPT...  register on Liveme the APP, verify with the link LiveMe.com sent in the email.. and use those credentials in LMPT.

**Comment by pinkystinky** [comment]
that worked perfectly! Thanks!

I'm having an issue with downloading now and i couldn't find a solution in the other threads. I downloaded ffmpeg but i get an error file isntead and instead the .txt is


'[
  {
    "code": "ENOENT",
    "errno": "ENOENT",
    "syscall": "spawn C:\\ffmpeg-4.0.2",
    "path": "C:\\ffmpeg-4.0.2",
    "spawnargs": [
      "-formats"
    ]
  },
  null,
  null
]'

do you know what i'm doing wrong?

please and thank you :)

**Comment by Xqqz** [comment]
@pinkystinky  see this #97

**Comment by ginnygin** [comment]
Anybody know of a place to share the vids from live.me.  Used to go to discord

**Comment by bigugly3** [comment]
I uninstall everything then reinstall 1.1.8 and my old email is still in there and when I change it,, it still says i'm not authenicated and goes back to my old email.  Are there files somewhere on my computer I need to delete that it is pulling from?
