### ISSUE TITLE
log in

### ISSUE THREAD

**Issue by shashoe** [Lewdninja/liveme-pro-tools#143]
authentication error 
correct details for login still error

**Comment by Xqqz** [comment]
@jamesey0682 
What VERSION are you using , 1.1.9 ?
Mac or PC ?

**Comment by jamesey0682** [comment]
hi i was trying 1.1.9 now i went back to 1.1.8 but still says i am not
autenticated im kind of new to all this still learning but i resd if u mske
new liveme account it works on 1.1.8 so about to try that

**Comment by jamesey0682** [comment]
its for windows 7 hi i was trying 1.1.9 now i went back to 1.1.8 but still
says i am not autenticated im kind of new to all this still learning but i
resd if u mske new liveme account it works on 1.1.8 so about to try that

**Comment by jamesey0682** [comment]
got it logged in eventually thnks
