### ISSUE TITLE
For the LATEST version of LMPT... CURRENT version -  go here

### ISSUE THREAD

**Issue by Xqqz** [Lewdninja/liveme-pro-tools#146]
Updated ::  https://github.com/thecoder75/liveme-pro-tools/issues

and join the Discord chat.

**Comment by macuser1000** [comment]
Not working

**Comment by Xqqz** [comment]
@macuser1000 
NotaBug.org is currently down
You can go directly to the Discord room here: https://discord.gg/A5p2aF4
