### ISSUE TITLE
Still can't authenticate

### ISSUE THREAD

**Issue by cmkeeper9** [Lewdninja/liveme-pro-tools#15]
Great tool and looking forward to the next update.  This version (1.1.5) does not work with authentication.  I entered my details properly and cannot pull any replays up.  Besides the email/password is there anything else needed to get this up and running again?

**Comment by seaoftheives** [comment]
It works great. What login are you using to sign in? If it's a login linked to a facebook, instagram or twitter account, it will not work. You must make a Live.me account using the mail icon on the home screen.

**Comment by batjew** [comment]
Also interested. Tried again today with a new account an i can not see replays still.

**Comment by cmkeeper9** [comment]
That fixed it.  Thanks seaoftheives .  Need to use mail icon .  Maybe the notes should be updated to reflect this so it is easier to understand for simple non techies :)
