### ISSUE TITLE
download doesnt queue immediately goes to error on MAC

### ISSUE THREAD

**Issue by stonedmonkey** [Lewdninja/liveme-pro-tools#17]
the setting on the app doesnt have link to ffmpeg option how do i make it download?

**Comment by Lewdninja** [comment]
Open up terminal and type ``ffmpeg -version``. What output do you get?

**Comment by stonedmonkey** [comment]
3.3.2

**Comment by Lewdninja** [comment]
Okay. I'll look into it soon.

**Comment by Lewdninja** [comment]
Try the new alpha version: https://github.com/Lewdninja/liveme-pro-tools/releases/tag/v1.1.6-alpha
If the download still fails there should now be an error log file in your specified download directory. Feel free to email me the log file lewdninjacom@gmail.com
