### ISSUE TITLE
Auto New Version Indicator

### ISSUE THREAD

**Issue by cmkeeper9** [Lewdninja/liveme-pro-tools#18]
Not sure if it was updated recently but the new version indicator is pointing to the old developer of the tool. it is helpful when a new version comes out it auto informs.. Simple feature but it is very helpful :)

**Comment by Lewdninja** [comment]
That's going to be fixed with the next release.

**Comment by Lewdninja** [comment]
1.1.6-alpha should fix this
https://github.com/Lewdninja/liveme-pro-tools/releases/tag/v1.1.6-alpha
