### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by izmore** [Lewdninja/liveme-pro-tools#19]
Please help me out with the installation. i have used this program may times without issue. i have a new computer and can't get it to work for the life of me. I cant get any replies at all from any live me user. Please help, I'm so frustrated. i have spent countless hours trying to get this running with zero success. Do you have a step by step file you can send me?

thanks in advance

**Comment by jonty123456** [comment]
im avin same trouble lost my token do know how to get it back you need live me pro tool to start there is a mega download for this i will try to find it

**Comment by jonty123456** [comment]
https://mega.nz/#!FAkS0TAK!GucRsZqp49_zRkK6eiQX9TPH29iU-Cb8SblgvhRXqrY)

**Comment by izmore** [comment]
Unfortunately the link is dead

Sent from my iPhone

On Apr 23, 2018, at 3:37 PM, jonty123456 <notifications@github.com<mailto:notifications@github.com>> wrote:


https://mega.nz/#!FAkS0TAK!GucRsZqp49_zRkK6eiQX9TPH29iU-Cb8SblgvhRXqrY)

**Comment by izmore** [comment]
my bad, the link works. Thanks for the quick response. I hope it works! I'll let you know, Thanks!

________________________________

**Comment by izmore** [comment]
so I installed the program from the Mega link and it still shows no replies. Do i need to install something else?


________________________________

**Comment by jonty123456** [comment]
sorry mate i think we will have to wait till they make a app with replays in

**Comment by dasheron** [comment]
@jonty123456 The problem is that LM changed their API and in order to view replays, you must have your login credentials.

**Comment by letsgohomes** [comment]
Why can I not find a email signup page on liveme.com or the app?  When I click on the email icon it just ask me to login.  Nowhere does it say "click here to register" just invalid username/pass.  Am I missing something? I've tried both on mobile and browser.

**Comment by izmore** [comment]
Thanks very much everyone

Sent from my iPhone

On Apr 23, 2018, at 4:31 PM, jonty123456 <notifications@github.com<mailto:notifications@github.com>> wrote:


sorry mate i think we will have to wait till they make a app with replays in

**Comment by dasheron** [comment]
@letsgohomes You need to open you phone app, logout from your main acc, then register a new account. You can ONLY do it using the APP.

**Comment by letsgohomes** [comment]
@dasheron I've opened the phone in the app, and the options I see are when I click on the app the following:

live.me (logo)  > recharge > question mark > sign in

Nowhere to sign up.  Weird.

**Comment by dasheron** [comment]
@letsgohomes I think you are opening the website from your phone. Those options only appear on the website. 
You must open the Live Me App on your phone and register from there.

**Comment by smagdan** [comment]
This isn’t a general help forum.. can we keep this area to actual development issues with the app.

**Comment by jonty123456** [comment]
can you tell me why whatever email i try to use on live.me it just keeps saying wrong password

**Comment by jonty123456** [comment]
sorry smagdan  dont know where else to go

**Comment by dasheron** [comment]
@smagdan Trying to help only! Remember, once we were newbies! 
@jonty123456 you must register an account with an email. 

Steps:
Open LiveMe APP.
Logout from your main account
Press "login with another account"
Press the email icon under "other login metod"
Input your email account 
Input your password
Verify your email account

Then, go to the Live Me Pro Tools app, go under settings and insert your new login details.

Done! You can now see replays.

**Comment by ddpk** [comment]
@dasheron Sadly I think no matter how many times you clearly explain it, they can't seem to figure it out. But half the blame goes to Live.me's poorly developed app and bonus blame goes to their shitty liveme.com site
