### ISSUE TITLE
Auto-saving & updating of bookmarks and their replays to local files

### ISSUE THREAD

**Issue by ddpk** [Lewdninja/liveme-pro-tools#20]
I understand probably a lot of work would have to go into having the tool constantly checking to see if new replays are made available for each and every bookmark then saving that information. I think the current scan of new replays is only triggered when opening the app and/or clicking the home button. Which obviously doesn't yet include saving of M3U8s and other information. Maybe this can become an advancement of what's already there.

**Concept:** 
Firstly, it would have to do constant scanning **(with the option to choose how often bookmarks are scanned)** and when needed, saving edits for each user to their file. Which would also require detailed **(Date & Time) (VideoID) (Length) (Views) (Shares)** saved info on each broadcast included in the file next to the M3U8 to know if its worth downloading since it's possible playback won't be available. (This feature would be kind of pointless without this additional info) Using the amount of **views**, number of **shares** , the video **length** or the **VideoID** to see if its been deleted or not as an indication to or not to download that replay. It would be helpful if it first saved all current replays in order starting **oldest dated replay at the top** of the file to **latest dated replays at the bottom** so it can keep adding the newest replays in order from the bottom. Keeping each replay and its info to one line each, then starting each line with the **[4-23-2018]** date, then **[15:40]** time would make it easy to navigate through and finding each new replay added. I don't know what kind of file would be used to neatly save so much information? JSON? Maybe instead of throwing every replay in one single file, in each users folder would be **separate files** for each replay. The **filename** being **[4-23-2018] 15245154872220088139.file** date of broadcast and VideoID. Then any additional information, like the M3U8 inside.

**This is a side idea and not to be taken seriously if not feasible:**
It would be very clever if there was a way for it to snatch the M3U8 each time the very second it is generated. Exactly 10:00 minutes after a broadcast ends (for myqcloud) the replay becomes available. Every time no matter how long the broadcast is, 8 seconds or 8 hours, it'll always take 10:00 minutes. This would probably require some kind of insane tracking of a bookmarked users live broadcast, noting the exact time it's ended. Then adding a 10 minute timer to that and checking that broadcast at that exact time for a 99.9% success rate of saving that M3U8. Even if the broadcaster is sitting there refreshing their replay list waiting for the broadcast to appear in order to delete it, this would still be faster and beat them. **(Exceptions are they're banned live, it's a ksmobile M3U8 or the uncommon bug where a myqcloud broadcast generates instantly and more than half of the broadcast is excluded from the replay.)** 

**Alternative idea:**
In addition (or alternatively) you can add a one time button like **"Create local files on all bookmarks"** then once they're created, replaced by button **"Update local files on all bookmarks"**. Which would additionally be used for scanning any newly added bookmarks and adding file(s) on them, meanwhile updating the currently saved files. If both manual and auto updating ideas are good, then adding both, with the option to let it auto update itself and an option to pick how often it scans, referring back to my concept. 

**Why add this feature?**
The feeling of having a way to save everything would be really nice because of how often deleting occurs and now even **expiring broadcasts** being a thing. I know expired replays only make it so you can't click them on mobile, but also puts them on a timer for deletion. As well as M3U8's lasting for a couple months so you have all the time you want to go through these saved files. Depending on if saving/updating is 100% accurate and how often you set the scan checks it would probably **secure every single replay**. Especially since it seems that most users are unable to see their own replay (to delete it) until after its been generated. So in that case, you'll be able to save every replay M3U8 to your file before they get the chance to remove it **without needing to be at the computer**.

**Potential issues with this feature and how they can be (hopefully) avoided**
The thought has also occurred to me that this could possibly be very **cpu/bandwidth intensive**. But then again, I wouldn't know how it would work. I don't know what the speed of the scans would depend on, fast internet? Fast computer? Would it scan every single user at once say.. every 5 minutes? That would probably break something if you had 500+ bookmarks. Unless, it quickly went through the list scanning each user one at a time? And what if it was just always **scanning 24/7**? Once it finished the list it instantly started again from the top? I'd like knowing how fast each scan currently is for checking for new replays, and how much it would slow down the scan if it were also adding/updating info to a local file at the same time. Would it also be checking over that file in order to **reject adding duplicates**? I wonder if this could be made to **operate quietly in the background** without being noticed during daily computer use.  

I probably sound a little crazy by now but I figured it would be nice to add in every thought and idea about this that I could. I'd be happy to help test it out if it ever came to be worked on. @Lewdninja I know there's a bunch of feature ideas/bugs being thrown at you and you're probably still not sure if you want to fully commit to working on this project yet. I don't know if this is even worth suggesting so if anything i'd just like to know your thoughts/ideas on it. Sadly, the most I can do right now to try and help is offer very detailed ideas or be a tester as I don't have any Cryptocurrency. **EDIT: Soon I will be becoming a patron. Just noticed you made one.**

I'm open to anyones thoughts about this (@thecoder75 you too!). I mainly shared this just to put the idea out there and possibly discuss it. This idea originally came from @nubcaek11's comment on a **"running list of all the m3u8s from bookmarks concatenated to a local file"**. Just thought I'd try and bring the idea to life. I also tried putting important parts in **bold**.

**Comment by thegeezer9999** [comment]
Hi ddpk

Even though you seem to diss everyone else's ideas, I am not going to stoop to that level, and so, since you asked for opinions, here is mine.
I believe you are over-complicating your requirements here, and that in any case, they should be separated into different requests. I also think that initial work being conducted should revolve around fixing bugs (priority ones first); looking to address download speeds WITHOUT adversely affecting reliability and consistency; and getting previously popular features back.
Most of what you are requesting here is functionality offered by LAMD, and I believe Lewd has this on his list to get back working. 
A clear warning on downloading of duplicates is a good idea for when the monitoring period has expired. So this would simply keep track of ALL downloaded and viewed bc forever, and I would see this as an enhancement of existing functionality, or at least using the current, understood methods to display these icons (Already downloaded, Already viewed but NOT downloaded would be the two options needed here).
Suggest you open a separate request for the duplicates ?

**Comment by ddpk** [comment]
@thegeezer9999 This wasn't really a request full of requirements rather brainstorming random ideas based on other programs I use had worked and how they could be useful here. I know it's too much so it's just something to read and talk about if anyone wanted to and might spark new ideas. Or if someone was making their own project and maybe wants to use something here, why not. I doubt most of these things will happen, because they're totally unnecessary and would just be making it easier to be lazy. I don't know if you meant the same thing I do about duplicates so I guess you can open it if you have better knowledge on it because I don't download through the tool (if that's what you meant)

**Comment by Lewdninja** [comment]
This is TL;DR for me. Please make separate smaller issues with your ideas & suggestions and keep them short and straight to the point.

You guys can keep on discussing here about the ideas and which ones should be formulated into actual suggestions that would improve this app.

**Comment by ddpk** [comment]
@thegeezer9999 Wow... I never knew what LAMD was or did until I just saw it forked by Lewdninja. I'm just now reading what it does. I honestly didn't know I was suggesting things that already existed on it. Maybe half if not all these suggestions are meant for LAMD. Most of what I thought of for liveme tools came from a periscope auto downloader. My bad

**Comment by tp9ine** [comment]
That seems very useful. But where is the forked exe? I see a zip file. A quick run down on how to use it, please?

**Comment by ddpk** [comment]
@tp9ine Not released yet I'm guessing. I think it stopped working properly as well and still needs to be fixed with login authentication. Also I have no idea how to use it. It's probably easy I just couldn't find out how myself
