### ISSUE TITLE
Unminimize bookmarks window when you click "view bookmarks" button and it's minimized

### ISSUE THREAD

**Issue by barakaka** [Lewdninja/liveme-pro-tools#22]
I mean when you already opened the bookmarks window earlier and click the button again when it's minimized, nothing happens and you have to click on the task bar to bring it up.  Not a big deal but a minor annoyance.  I'm on Linux in case it's just on that.

**Comment by Lewdninja** [comment]
Will be fixed in the next release.

**Comment by Lewdninja** [comment]
Fixed in next release, or just pull the newest commit if you're running it with source code.
