### ISSUE TITLE
Download error in the end(1.1.6-alpha release)

### ISSUE THREAD

**Issue by vero6** [Lewdninja/liveme-pro-tools#24]
Whenever I click on the download button,the chunks start downloading but once they finish downloading i get a **Download Error** sign.HELP
![imageedit_2_9335873488](https://user-images.githubusercontent.com/38718290/39235027-742cb620-4892-11e8-85e5-1009154de21a.gif)

**Comment by Lewdninja** [comment]
Feel free to use the **1.1.5** version. You're using the **alpha** version which uses a different download method right now.

**Comment by Lewdninja** [comment]
Try this release, which is also alpha, it should generate a log file after FFMPEG fails to convert the downloaded chunks.

https://github.com/Lewdninja/liveme-pro-tools/releases/tag/v1.1.6-alpha.1

**Comment by Lewdninja** [comment]
Since OP hasn't responded in a while I'm closing this. Could also be related to https://github.com/Lewdninja/liveme-pro-tools/issues/43
