### ISSUE TITLE
1.1.6-alpha.1 - issues - no download features | LAMD not saved | version incorrect

### ISSUE THREAD

**Issue by simonwood1** [Lewdninja/liveme-pro-tools#26]
A few issues with 1.1.6-alpha.1 (exe) release:

- the DL implementations are not in the
- LAMD setting selections are not saved
- version is shown only as "1.1.6-alpha" , not "1.16-alpha.1" as it should

Keep up the awesome work!

**Comment by Lewdninja** [comment]
The DL implementation will be in the next release, need to add a few more things before that.
LAMD hasn't been updated to work yet anyway.
Not really an issue right now.

**Comment by Lewdninja** [comment]
I've updated LAMD but I have not tested it, neither can I make builds for it right now.
https://github.com/Lewdninja/lamd
