### ISSUE TITLE
Pause Downloads

### ISSUE THREAD

**Issue by mmind99** [Lewdninja/liveme-pro-tools#29]
Would it be possible to add a pause button in the download queue?  Many times I have to close out of the app before all of my downloads have completed.  When I reopen it, all of the queued downloads are gone.  It would be great to hit the pause button before closing the app, and it then retain them next time I start LMPT.

Thanks for all the hard work!!

**Comment by Lewdninja** [comment]
Pausing an ongoing download is going to be a headache. I could possibly add a way to save the queue itself and it'll start re-downloading replays it didn't finish before.

**Comment by mmind99** [comment]
Not really worried about picking up in the middle of a download, retaining the list after shutting down would be fantastic!  That was my main concern, I didn't word that well.  Thanks a ton!

**Comment by thecoder75** [comment]
One of the last updates I did was to add an auto-save to the current download queue for resuming upon restart to both the LiveMe Pro Tools and LAMD.  It should be working unless changes to the download section changed this.

**Comment by Lewdninja** [comment]
@thecoder75 can you link me to the commit that introduced that functionality?
