### ISSUE TITLE
import favorites

### ISSUE THREAD

**Issue by vasilismf** [Lewdninja/liveme-pro-tools#31]
Hello, is there any way to import favourites list (favourites.json file) from the liveme tools application into the live me tools pro application? The import favourites setting does not seem to support .json files!

**Comment by Lewdninja** [comment]
Since I haven't used export/import I don't know how that file I structured. If I'm to add json exporting and importing I need references.

**Comment by thegeezer9999** [comment]
Hi Lewd

Thinking more about this, could be a useful start up option. So user new to LMPT but has tons of follows in LM. The tool would offer a nice option to import Follows into Favourites (so it would under the hood run an export of Follows to json, then import that json to create your Favourites list. The other option would be (as current) start with a blank Favourites.
