### ISSUE TITLE
Automatically download chat .txt with videos

### ISSUE THREAD

**Issue by barakaka** [Lewdninja/liveme-pro-tools#33]
liveme-toolkit had this and this and I miss this feature.

**Comment by mmind99** [comment]
I was the one who requested this on LMTK.  Definitely a useful feature.

**Comment by smagdan** [comment]
I didn't know this was a feature that would be really cool

**Comment by Lewdninja** [comment]
Will add this as an option in the next release.

**Comment by gitaclysm** [comment]
You could also format them as SRT subtitles, them you can see while playing the downloaded video who said what and when.

**Comment by tp9ine** [comment]
@Lewdninja Is there a URL that can be used to access the chat log?
