### ISSUE TITLE
Logs of the homepage new replays

### ISSUE THREAD

**Issue by ddpk** [Lewdninja/liveme-pro-tools#34]
It seems once you've viewed the homepage of which new replays are available, once you leave that or "refresh" it, it all goes away. Also if you're already viewing that persons ID with that new replay on it, it won't show up on the homepage. It would be nice to have everything always stay there as history with the option to clear it when you're done. It also sometimes picks up as a new replay (x minutes ago - being how long ago they went live) when they go live. Which brings the idea of why not add this for live and replay broadcasts? To make it easier, when you click on them it opens from the video ID instead of user ID so it highlights it in blue 😃

**Comment by ddpk** [comment]
Actually, it also won't show up if you're viewing their profile while that broadcast is live

**Comment by ddpk** [comment]
Yeah, it works but could possibly be even better. Replays can just get lost too easily, then deleted before found again. But maybe at a later time.

**Comment by Lewdninja** [comment]
Will look into improving the new replays functionality in the future. Will keep this issue open until I've done so.
