### ISSUE TITLE
Mac Download Error

### ISSUE THREAD

**Issue by latenate16** [Lewdninja/liveme-pro-tools#36]
I'm assuming this is a ffmpeg issue but i know next to nothing about how it's installed.  It was working in a previous version of Toolkit.

In 1.1.5 when I try to download it gives an immediate Download Error.  In 1.1.6a the file downloads completely - I can see all the .ts files being generated.  When it's done is when i get the Download Error and a text .log file is created.  Inside the text file is.
[
  {},
  null,
  null
]

I installed Xcode and used that to install ffmpeg.  in usr/local/bin i have what looks like symbolic links for ffmpeg and ffprobe.

Any thoughts what i'm doing wrong?

**Comment by Lewdninja** [comment]
Another MAC users who has the same problems uses this workaround:

> instead of opening the app like normal, on mac, if you right click the application then select "open package contents" then open "mac os" then put the file "Liveme-Pro-tools" into terminal and run it.... this somehow finds ffmpeg for the app...

**Comment by latenate16** [comment]
That works.  Still have intermittent failures but now it's not 100%. Thanks for all your hard work on this project.
