### ISSUE TITLE
Playing replays show black screen in Windows 7

### ISSUE THREAD

**Issue by jikhogg** [Lewdninja/liveme-pro-tools#38]
Hello everyone. When I try playing any replays from the app, it shows the video player popup, it has a sound but the actual video is just a black screen. Can anyone give me any ideas how I can fix it. I tried various things but with no result.

**Comment by Lewdninja** [comment]
1. Are all the videos black /w sound?
2. Have you tried using a custom player in the settings to fix the issue? (VLC is pretty good)

**Comment by orion0469** [comment]
I am having the same problem. I try to set vlc as the player but the %url% is ambiguous. vlc is in the default location but to get this to play I have tried every option I can think of C:\Program Files\VideoLAN\VLC mp4 %url%   am I suppose to choose the url for each? i have tired everything. I am quite a n00b. any assistance would be greatly appreciated.

**Comment by pepzwee** [comment]
``C:\Program Files\VideoLAN\VLC\vlc.exe %url%``

**Comment by Lewdninja** [comment]
``C:\Program Files\VideoLAN\VLC\vlc.exe %url%``

**Comment by jikhogg** [comment]
Every video has sound, yes. And the whole player controls are working. I can rewind it and change the volume, but the picture is black screen.

**Comment by orion0469** [comment]
in settings i put that string C:\Program Files\VideoLAN\VLC\vlc.exe %url%  I click watch replay nothing happens  I click URL nothing happens  ..I know i am missing something simple.

**Comment by Lewdninja** [comment]
Use this (also edited previous comment), forgot to add quotes.

``"C:\Program Files\VideoLAN\VLC\vlc.exe" %url%``

**Comment by orion0469** [comment]
That was the money. Thank you. I knew I was missing something simple.

**Comment by Xqqz** [comment]
I'm running Windows 7 Ultimate - 64bit
No issues with videos using LiveMePro Tools default settings.
Built in player is working fine.

**Comment by Lewdninja** [comment]
Closing this as OP didn't respond any further.

**Comment by jikhogg** [comment]
Thank you very much Lewdninja, the alternative player worked. I still have black screen with the in-built one, but at least I can use the external.

I was not at home yesterday, so I was unable to answer your message. Sorry for any inconvenience that I might have caused.
