### ISSUE TITLE
A way to enter token instead of email/password.  Or log in via social media

### ISSUE THREAD

**Issue by barakaka** [Lewdninja/liveme-pro-tools#4]
First, thanks for updating this.  

I currently don't have a smart phone.  And there is no way to sign up for live me with an email address without a smart phone as far as I can tell.  I can log in with instagram though and am able to see what my androidid, uid, tuid, and token are through firefox web console.  Can there can be an option to enter these into the settings instead of the email & password?  I might be able to figure out how to edit them into the code manually but this would be more convenient.  And maybe a few other people could use this.

**Comment by starsaillor** [comment]
If you don't own a smartphone, one way of logging in is by using NOx, it's an Android simulator, I use it here, and it works fine

**Comment by batjew** [comment]
Hmm I must be doing something wrong i tried logging in with a twitter account and created an email through nox but i still dont get replays.

**Comment by Lewdninja** [comment]
@batjew You have to register an account on Live.me using the email method.

**Comment by batjew** [comment]
I did using Nox and mail.com lol. I activated the account and logged in through nox. I must be doing something wrong it still says bookmarks being scanned for new videos. I just restarted my computer just in case but nothing. I can give you the email address and password to see if it works anywhere else.

**Comment by ddpk** [comment]
@batjew You said you signed up with twitter are you sure you didn't click the icon to sign up solely with an email address and not through another app like twitter, instagram or gmail?

**Comment by batjew** [comment]
No it was just the email icon. I shall try again though thats a good point

**Comment by barakaka** [comment]
There's a section in the protools settings called Authentication where you enter your email and password.

**Comment by SteveKajak** [comment]
I can not log in to Live.me app via e-mail or nox via smartphone. No confirmation e-mail will be sent to the specified e-mail address. Why ? What am I doing wrong ? Do only certain mail servers work? Can someone give me his login information (fake email account access)? Thank you very much !

**Comment by seaoftheives** [comment]
@SteveKajak  It seems Live.me doesn't like certain email providers. I was unable to receive a confirmation email to this first email address I used even though live.me said it was sent. You'll just have to try a different provider.

**Comment by SteveKajak** [comment]
@seaofthives  gmail.com works for Registration, but its not for using a fake account.

**Comment by starsaillor** [comment]
Guys, I didn't need to use an email account, I simply logged into the liveme app using my Google account, then used the same email on pro tools, worked like a charm.

**Comment by seaoftheives** [comment]
@SteveKajak I would try heading to yopmail.com. I've always had good luck with those throwaway email addresses.

**Comment by knock43** [comment]
If you login to pro-tools then in to the website (liveme.com) or the official app on your phone, using the same account, your token expires, thus breaking pro tools.  I'm assuming a new token is made every time you restart pro-tools but I haven't test that personally.

So, sharing accounts wouldn't work.  I'd suggest making an account STRICTLY for pro-tools to eliminate this from happening.

**Comment by ddpk** [comment]
@knock43 I also notice every time I restart the pro tools it stops working so all I do is go to the settings for a few seconds click the field boxes and then click the X and it reauthenticates. Don't know which part does that but I still do all 3 steps

**Comment by ddpk** [comment]
@ryandunning1 Try this https://github.com/Lewdninja/liveme-pro-tools/issues/37#issuecomment-385051555

**Comment by amr18379** [comment]
Someone can help and provide the correct link to view the replays in case if i have the token ,how can i add the missing parameter of the token  to display the web page without any missing parameter message

http://live.ksmobile.net/live/getreplayvideos?userid=

**Comment by Lewdninja** [comment]
Not going to implement other authentication methods.
