### ISSUE TITLE
Feature request - Concurrent/simultaneous downloads

### ISSUE THREAD

**Issue by simonwood1** [Lewdninja/liveme-pro-tools#40]
No matter how fast your connection, a real weakness with this app which is caused by slow streams is the absence of a simultaneous downloads feature - without it, sequential downloads turn into week long exercises (during which some replays may be deleted before the queue catches up).  I realize that this used to a feature once but was removed due to "FFMpeg" - not sure why that's issue - other products seem to manage it whilst using FFMpeg. 

I know you have your hands full @Lewdninja but if you could consider this, it would be greatly appreciated!

**Comment by tp9ine** [comment]
If i'm not mistaken, this was added? It's a good idea, however, for those with relatively low bandwidth (30Mbps) it has a negative impact as it makes any one of the concurrent downloads take much longer to finish as it sharing the speed among all of the active downloads.

Will there be an option to set how many active downloads going at once?

**Comment by ddpk** [comment]
If you have to just use an alternate download method like Internet Download Manager to save yourself the struggle. I have broadcasts queued in this thing that have been deleted a month ago and still have them sitting there able to download whenever I find the time.

**Comment by mmind99** [comment]
With the new slower more stable download method, this would be a game changer.  I let my queue run all night and still didn't get all of them downloaded lol.  Even if we could do 3 at a time, it would be fantastic!

**Comment by Lewdninja** [comment]
Concurrent downloads release is published on Patreon. It will be pushed to Github in a week or so.
