### ISSUE TITLE
Liveme Pro Tools: It does not show me the repetitions.

### ISSUE THREAD

**Issue by LordDani** [Lewdninja/liveme-pro-tools#42]
As the title says when I put the ID of the video or the ID of the user does not show me the repetition of the ID nor the other repetitions. Any idea why? or has that still not been solved?

Thanx :)

**Comment by tp9ine** [comment]
Did you authenticate by typing in your liveme email and password in the settings?

**Comment by Lewdninja** [comment]
I'm going to guess you didn't authenticate under settings. Going to close this but feel free to comment here and if it's an actual issue I'll re-open it.
