### ISSUE TITLE
Instant Download Error

### ISSUE THREAD

**Issue by artorawley** [Lewdninja/liveme-pro-tools#43]
I've seen this on multiple versions now, I click the download button and get an instant Download Error. I've changed download path, changed download naming convention, still the same result. I have FFMPEG installed and it works for other apps, not sure why it's not working for this one. Is there a way to manually point this app to FFMPEG like TheCoder's old LiveMe Tool could? My best guess at this point is that it isn't finding my FFMPEG folder for some reason.

**Comment by mmind99** [comment]
Check and make sure you have a \ at the end of your download path.  Think that caused a similar problem for me.

Correct - C:\Downloads\Vids\
Incorrect - C:\Downloads\Vids

**Comment by scozz76** [comment]
Add ffmpeg to the system path.
Right click 'this computer' (desktop) & select 'properties
"Advanced System Settings"
"Environment Variables"
In the 'User variables for <user>' double click "Path"
Add the path to your "ffmpeg\bin" directory (in my case it is "c:\windows\ffmpeg\bin").

Check that it is all working by opening command prompt in administrator mode and type "ffmpeg -version"

**Comment by Lewdninja** [comment]
You can also specify FFMPEG path in settings manually now.
