### ISSUE TITLE
Problems with firewall

### ISSUE THREAD

**Issue by clehmann-geo** [Lewdninja/liveme-pro-tools#45]
Hello,

I am unable to use livemeprotools together with a firewall. I can neither see the feed nor search for usernames etc.

I already enabled the .exe file in the Windows firewall, but that still did not solve the problem. Are there any ports I have to open manually? Btw the livemetools by polydragon have worked for me despite the firewall.

Thanks in advance for help!

**Comment by clehmann-geo** [comment]
On another PC without any firewall enabled the liveme-pro-tools work without problems.

**Comment by smagdan** [comment]
You need to login.

**Comment by ddpk** [comment]
If you already have it added to the firewall (which I don't think is even necessary) how do you know its a firewall issue? If you're referring to an older version that worked "despite the firewall" maybe you don't yet know about needing to login?

**Comment by clehmann-geo** [comment]
@ddpk Yes, I am aware that I need to login to see the replays and download, but on this PC with firewall (and I think also running through a proxy) I can´t even see the feed on the right side of liveme-pro-tools, also I can´t connect to my liveme account or search for users. So I think its a network issue. As I said, the same version of livemprotools works fine on my personal PC, and the livemtools by PolyDragon also worked without problems (until the need to login introduced recently).

**Comment by thegeezer9999** [comment]
Check your firewall rule to make sure it is enabled for the right network. U can also set up firewall logging to catch the block.

**Comment by clehmann-geo** [comment]
Okay, I will give it a try. Thanks!
