### ISSUE TITLE
problem with number of replays

### ISSUE THREAD

**Issue by TuxNuX** [Lewdninja/liveme-pro-tools#46]
on liveme pro tools 0 replays
![screenshot_20180430_162037](https://user-images.githubusercontent.com/17123357/39432219-298cbd0e-4c93-11e8-9598-0b1856ed9c2a.png)

on this site more than 30 replays
http://www.ulivetube.com/index.php?livechannel=954784328439701504

same problem with many other users
I had already noticed this problem since the change of  API 
the website only confirms this loss of replay

**Comment by Lewdninja** [comment]
uLiveTube archives broadcasts - this app doesn't. Broadcasts can get marked hidden and/or deleted thus they will no longer appear.

**Comment by TuxNuX** [comment]
yet the server, the links du website des replays are the same 
they seem to come from the official cloud of liveme

**Comment by Lewdninja** [comment]
Replay files get deleted later.
