### ISSUE TITLE
Discrepancy when jumping/fast forwarding in videos. Manually concatenating produces better results?

### ISSUE THREAD

**Issue by tp9ine** [Lewdninja/liveme-pro-tools#47]
I'll try to keep this as short as possible, hopefully it doesn't turn too much into a tl;dr.

First off, I use Media Player Classic to view videos and have hotkeys setup to ff/rewind. 

While checking out videos that were downloaded with the newer version(s), versus downloaded with 1.1.5, I noticed there was a significant difference in their abilities to fast forward.

Videos downloaded with 1.1.5 seek instantaneously while ones downloaded with newer version(s) have a noticeable lag time before the video seeks/playback starts (most noticeable when you spam the hotkey a few times). It is about a few hundred milliseconds difference which may not seem like much, but really becomes a pain after a while. 

At first I thought it was just an issue with the broadcaster's stream, but when every single new download displayed this issue, I knew something was up.

However, thanks to the new feature to keep the temporary files, I tested a few times, to manually concatenate the video chunks, and the output was much better than their original counterparts.

Is this something that can be improved?

**Comment by ddpk** [comment]
If you are indeed talking about playing back the downloaded video, the best video player that truly preloads any long broadcast is GOM player. It's not the cutest interface but it gets it done. It's no secret that VLC and other video players fall short with liveme video files, sometimes no matter how good of a computer you're running it on. But I can't comment on the difference between versions. Unless it was from the change in adding ffmpeg? All i'm getting at is it might be worth testing GOM player over media player

**Comment by Lewdninja** [comment]
All depends on how you concat them. Current settings shouldn't break bad quality replays (lossy, bad chunks etc..) when combining the chunks.
