### ISSUE TITLE
Feature request - Resume downloads after crash

### ISSUE THREAD

**Issue by simonwood1** [Lewdninja/liveme-pro-tools#48]
After the app crashes (usually when using the 'unstable' but wickedly fast 'chunk' method) it would be great if it could resume the queue of downloads. Currently after restarting, the queue is lost

**Comment by Lewdninja** [comment]
Umm.. how is the app crashing?

**Comment by simonwood1** [comment]
It throws a JS error in a large dialog box. I thought you were aware of this, hence the 'unstable' comment about chunk downloads. Do you need a screenshot?

**Comment by Lewdninja** [comment]
I would like a screenshot to see if it's intended or not.

**Comment by smagdan** [comment]
The chunk method isn't really that much faster (if at all).. it downloads quicker but then takes awhile to convert.. and the converted file has some missing data. think should just stick with ffmpeg

**Comment by barakaka** [comment]
ffmpeg is super slow for me, like I might as well play the video and screen record it slow.  Am I doing something wrong?  chunk method is fast though.

**Comment by simonwood1** [comment]
@smagdan if you haven't a decent CPU, the chunk method is way faster because it seems to download concurrent parts of the stream and put them all back together. The non-chunk method downloads each bit sequentially. The difference can be up to 30x faster - am I right @Lewdninja ?
