### ISSUE TITLE
Search bar on bookmarks list and following/followers 

### ISSUE THREAD

**Issue by ddpk** [Lewdninja/liveme-pro-tools#5]
It seems the search feature was replaced by the country selection. That's all.

**Comment by Lewdninja** [comment]
I'm not quite sure what this issue is about..?

**Comment by thegeezer9999** [comment]
This is definitely a good request, BUT cannot be at the expense of Country serach - this was a critical addition. The new search option should allow search by userID or UserName.

Thank you

**Comment by ddpk** [comment]
@thegeezer9999 What neat ideas is the country selection being used for? And is that only for following/followers list? 

What I had in mind for the searching was a simple Ctrl+F and enter in groups of letters and it narrows down the list as you type until you find what you're looking for kind of thing, y'know? I don't know if that's similar to how the old one was, I forget. 

Sometimes I'll see this type of search on programs or sites and it only works if the letters you type are the beginning of the name, not middle or end. So if you typed in "Bar" you'll only find "Barcelona1999" and not "Wheelbarrow69". 

 If anything i'm guessing the code from the old liveme tools could just be added to this? If anyone plans on making their bookmarks their new following list then this is very helpful!

**Comment by thegeezer9999** [comment]
Hi

Yes, that is exactly how the search used to work, it is useful where the target user has tons of followers, you go through them, call it a night, and want to resume next day (for example). In this case, you just note down where you got to, then search for that next day. The narrowing list was also really good and useful.
Country selection sacrosanct - there are many who only search specific countries :-)

**Comment by Lewdninja** [comment]
@ddpk just scroll down, until it loads more and then search.
