### ISSUE TITLE
unable to authenticate

### ISSUE THREAD

**Issue by Lockdown212** [Lewdninja/liveme-pro-tools#54]
I created a brand new email account, and signed it up on live me. It works fine on their site with the exact same credentials, but will not work in pro tools. Every time I try it says I am not authenticated and directs me to the settings page. Yes I'm sure it was created under their email login section, and I've even tried pasting the credentials to ensure I didn't make a mistake retyping the password.

**Comment by Lockdown212** [comment]
Never mind, I found the source of the problem. The settings file wasn't properly updating, so I had to go in and edit it manually to get it to reflect the proper credentials.

**Comment by Ironjunkie23** [comment]
Hey Lockdown212 - i know you've closed this issue but I'm struggling with the same thing. How did you manually edit it? (I'm totally new to coding - I don't really know the basics that well) Would appreciate the help
