### ISSUE TITLE
keeps saying "starting download..." on Mac

### ISSUE THREAD

**Issue by donalddumped** [Lewdninja/liveme-pro-tools#56]
can someone help with what the issue could be? replays play fine but can't download

**Comment by tp9ine** [comment]
You have ffmpeg.exe set up properly?

**Comment by ddpk** [comment]
https://www.youtube.com/results?search_query=install+ffmpeg+mac

**Comment by donalddumped** [comment]
ffmpeg is installed via brew, no issues in previous builds but only started recently.

**Comment by donalddumped** [comment]
fixed via launching app from terminal as suggested as a workaround in a different thread.
