### ISSUE TITLE
Mac Support

### ISSUE THREAD

**Issue by dasheron** [Lewdninja/liveme-pro-tools#6]
It will be nice for mac users to have a dmg file to download! Great work!

**Comment by ginnygin** [comment]
dasheron did you find away to make it work for mac. trying to figure out.  can you email me ginnygin12345@gmail.com had some questions.  Thanks man.

**Comment by dasheron** [comment]
@ginnygin , tried to figure out how to do it, but way too complicated. Even tried to use Wine, no luck.

**Comment by barakaka** [comment]
You have to build it yourself.  It's not too difficult.  Instructions:

-go to nodejs.org/en/download.  Install the mac installer with default options.
-open your Mac terminal and type:  npm install electron
-go to the liveme-pro-tools github page and click "clone or download" and unzip that somewhere
-open terminal and change directories (with cd) to the liveme-pro-tools-master folder
-type: npm install
-type: npm start

and it should run

**Comment by dasheron** [comment]
@barakaka Thank you very much! But for some reason I installed an old version, and I tried with the latest, but keep getting errors. 

npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/Lewdninja/liveme-api.git
npm ERR! 
npm ERR! xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
npm ERR! 
npm ERR! exited with error code: 1

**Comment by barakaka** [comment]
try the suggestions posted here for that error: apple.stackexchange.com/questions/254380/macos-sierra-invalid-active-developer-path

**Comment by dasheron** [comment]
@barakaka amazing! working perfectly now! Thank you very much

**Comment by Lewdninja** [comment]
Won't be working on dmg releases right now as I stated here https://github.com/Lewdninja/liveme-pro-tools/issues/3

As stated above just download the source and run it.

**Comment by ginnygin** [comment]
Where do you put in email address and pass to get it to start working.

**Comment by Lewdninja** [comment]
**Mac version now available under releases**
https://github.com/Lewdninja/liveme-pro-tools/releases
