### ISSUE TITLE
No Replay downloads works with lamd-1.3.2 at new Version 1.1.8

### ISSUE THREAD

**Issue by SteveKajak** [Lewdninja/liveme-pro-tools#63]
I still have the problem with the new version 1.1.8 that I can not download replays. With lamd-win 1.3.2 the error message comes:
(node: 1260) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4 ): Error: 400 Message: lack params: token

What am I doing wrong ? what can i do to get downloads again?
Many thanks for your help !

**Comment by Lewdninja** [comment]
Stop using LAMD.

**Comment by SteveKajak** [comment]
@ Lewdninja many thanks... ok.. Now i do not use lamd anymore, but if i use the internal downloader via ffmpeg then the download does not start and i get a javascript error every time.
What do I have to note in the settings to make it work?
