### ISSUE TITLE
1.1.8 has great new features, but is still highly unreliable

### ISSUE THREAD

**Issue by simonwood1** [Lewdninja/liveme-pro-tools#65]
@Lewdninja nice work on the latest build. Unfortunately though, numerous javascript errors mean that it very unreliable. With 30 or more in the download queue, any one of the following issues kill either the download, or more typically, all the downloads in the queue that follow it.

"Uncaught exception - Error: Callback was already called"
"ENAMETOOLONG"
"ENOENT"

**Comment by ddpk** [comment]
I still don't get why people use this app to download replays as well as browse for replays when there are way easier and reliable methods. Sure it's a simple click and you're done but clearly that doesn't go without it's flaws. Maybe if this doesn't work the way you need it, look into alternative download managers. They're very simple to use

**Comment by vero6** [comment]
Sir, would you be kind enough to suggest the other alternatives if you don't mind me asking ?

**Comment by TuxNuX** [comment]
I find version 1.1.8 well
but i think multi download and conversion be a bad idea, really very high cpu usage during the conversion
button "cancel" "delete" really miss 
pause button too would be fine
for multi download and conversion an option in the settings ON or OFF would be fine, or else a button start/pause on each file in queue

**Comment by ginnygin** [comment]
Can anybody put up a download for mac.

**Comment by mmind99** [comment]
I'm not seeing all the problems you are.  Think I've seen a java error once and it was likely self induced.  

I've used this and JD2 both to download, and by far I prefer this.  Its a little slower, but the end result is the same and I don't have to think about renaming.

**Comment by Lewdninja** [comment]
1. I can't do anything with the errors you pointed out in the first post since you didn't provide the full trace.
2. Queue concurrent download amount is completely in your hands since you can change that value in the settings. If your computer can't handle it, lower the concurrency.
