### ISSUE TITLE
Using tool logs you out of Liveme app (can't use concurrently anymore)

### ISSUE THREAD

**Issue by artorawley** [Lewdninja/liveme-pro-tools#66]
On 1.1.8 and can no longer use the tool while logged into the LiveMe app. When the tool does an auth check it logs me out of the app, and then logging back into the app pretty much breaks the tool and it will no longer auth without restarting it (which then logs you out of the app again). Any way to fix this so that it behaves like it used to so that we can use the app concurrently with the app open on the same account? Or did the latest API change make that no longer possible?

**Comment by starsaillor** [comment]
Don't see how's that really important, IMHO u dont need the official app when u have such a wonderful tool at your disposal

**Comment by knock43** [comment]
Make another account for Livemetools.  Simple as that.  Your token changes every time you reopen Livemetools or login to the official app.

**Comment by artorawley** [comment]
The tool doesn't completely replace the app, though. The app has push notifications while the app doesn't, the app also has messaging and other features that the tool doesn't have. Mainly, this used to work and now it doesn't. I don't agree with this dismissal.
