### ISSUE TITLE
New authentication method invalidates old tokens

### ISSUE THREAD

**Issue by gitaclysm** [Lewdninja/liveme-pro-tools#69]
Thanks for reacting so quickly and implementing the new login method.

Unfortunately, every time liveme pro tools are started, a new token is obtained, invalidating any tokens obtained previously. This makes it really hard to use alongside any other liveme tools that also require authentication, since logging into one will log you out of the other. I imagine this would also be a problem with using LAMDs active scanning for new replays.

Would it be possible to let us either enter a token/sso_token pair to use manually, or store the tokens on disk so they can be reused next launch, and shared between tools?

The only way to work around this is to create a separate account for each tool 😐

**Comment by artorawley** [comment]
I raised this issue and it was prematurely closed. Hopefully this gains more traction as I strongly disagree with the dismissal from earlier.

**Comment by ddpk** [comment]
Is it that hard to just make a new account for each thing you use? Wouldn't that solve it? Yes it's inconvenient but it's still a solution!

**Comment by gitaclysm** [comment]
It kind of solves the problem, but being able to use the same account across multiple tools could enable nice things. 
For example, I have an automatic downloader similar to LAMD which uses the API to get a feed of new live broadcasts from any users I follow - whereas LAMD has to individually poll all interesting users for new replays.
To add someone to the list, I can follow them in the app, or use a tool.
But these things can't work together if they can't share access to the same account.

**Comment by Lewdninja** [comment]
This is not a priority but I will eventually probably add a way to manually insert your tokens.

**Comment by amr18379** [comment]
Kindly how i can add the missing parameters to the old link

http://live.ksmobile.net/live/getreplayvideos?userid=X

X as the user ID but what are the other missing parameters !!! and how i can add them to the link to view  the records in the site.

**Comment by Lewdninja** [comment]
Look at the liveme api repository
