### ISSUE TITLE
Can't see replays again

### ISSUE THREAD

**Issue by thedude1999** [Lewdninja/liveme-pro-tools#7]
Everything was working about an hour ago with the new log in. Now it says "Account no longer available" when i click any replay

**Comment by barakaka** [comment]
This happened to me and I just added an x after my email address in the settings to test and it started working again?  Don't know why.

**Comment by smagdan** [comment]
It's because it wasn't auto logging in.. have to manually do it after restart. He already fixed this issue earlier today.

**Comment by Lewdninja** [comment]
Fixed in https://github.com/Lewdninja/liveme-pro-tools/commit/273d178e13105e4875d22fb6f894751ac01071b6
