### ISSUE TITLE
Second Following List

### ISSUE THREAD

**Issue by mmind99** [Lewdninja/liveme-pro-tools#71]
Would it be difficult to add a second following list?  In LMTK, we had a two separate lists, Favourites and Likes.  I used one to actually follow and keep track of users.  The other I used as a list of accounts I followed to get recommended users to look at.  

In this case, I would leave the bookmarks list as it is with the functionality of grabbing new replays.  And just add a simple Favourite list that doesn't track updated replays.  

Thanks!

**Comment by rebuff10** [comment]
you make sense like for now the people we follow to get to see their followings to decide who to bookmark or get replays from is actually merged in a single bookmarks section with the followings of us we bookmark.But you need to explain your request in  a manner that developers can understand you then only they will work on it

**Comment by mmind99** [comment]
Thought I did explain it...

Leave the Bookmarks list alone, it works fine.  Add a second list called Favorites or Following or whatever you'd like to call it.  The second list doesn't need to check for updated replays like the Bookmarks list does.  Just would like to have two separate lists.
