### ISSUE TITLE
Error! You are not authenticated...

### ISSUE THREAD

**Issue by demondecon** [Lewdninja/liveme-pro-tools#73]
Over the past 3 days I've been having issues with the Mac version Liveme Pro Tools with seeing replays.  This was working prior to 2 days ago without issues.

I've confirmed the username and password are correct (through directly looking at the settings file).  I've also tried removing the entire settings folders, and going with a fresh install of version 1.1.7 to no avail. While no error was occurring in version 1.1.5 which I was previously using I'm now getting the following error "Error! You are not authenticated, please enter your login details under Settings"  This is after I've already inputted the login details and confirmed they are correct (I've even tested this by logging into both the mobile app, website then back into the Liveme Pro Tools.

Any help would be greatly appreciated.  Thank you for continuing to develop this application.

**Comment by Hydrobolt** [comment]
After installing: "The file does not have a program associated with it for performing this action."
Then it promptly deleted the desktop icon.

**Comment by demondecon** [comment]
@xqqz no dmg file for Mac for 1.1.8 otherwise i would try it

**Comment by beachsurfer** [comment]
All of a sudden I'm getting this errom message too. I'm using 1.1.7 MAC version whilw waiting that some gury will compile 1.1.8 and make it availabale.
Thanks for supporting

**Comment by Lewdninja** [comment]
https://github.com/thecoder75/liveme-pro-tools/issues/13

I'm not stopping ``dmg`` files from compiling through Travis or Appveyor. Either they release or don't.
**I don't have a MAC computer to debug any potential issues so it's not supported and all related issues will be closed.** There's too many mac issues popping up and it's annoying since none of them are actually helpful.

**Comment by marcusi23** [comment]
Hi.
Im on windows 10 and i downloaded 1.1.9 yesterday and got the error "Failed to authenticate with live.me servers (invalid credentials)". Ive tried multiple accounts for a while checked them before inputting them into the app to confirm information was correct. Eventually it did work after like 15 min. dont know if it was something i did or what. today after restarting pc its comeback with error. has anyone else had this problem and have a solution.
thank you and thx for the continued work on the app.
