### ISSUE TITLE
Instant Download Error (Error log inside)

### ISSUE THREAD

**Issue by lifesuckz69** [Lewdninja/liveme-pro-tools#75]
So I never could download in any version and now I decided to try and find a solution.
I checked the other 2 closed issues about it and did everything there (enviroment variable, input the path manually, left it at automatic, put ffmpeg into windows or a ffmpeg folder inside windows, did a \ at the end) but nothing works.

Error log:
```
[
  {
    "code": "ENOENT",
    "errno": "ENOENT",
    "syscall": "spawn C:\\Windows\\ffmpeg\\bin\\",
    "path": "C:\\Windows\\ffmpeg\\bin\\",
    "spawnargs": [
      "-formats"
    ]
  },
  null,
  null
]
```

Not sure if it's supposed to do that, but I realize that in the error it doubles all the \. In the custom path it only has 1 and automatic also shows 2 in the error log.

**Comment by TuxNuX** [comment]
put file or folder in c: \ windows be always bad idea
access problem and asking administrator rights
try to reinstall ffmpeg as indicated on this tutorial
https://www.wikihow.com/Install-FFmpeg-on-Windows

**Comment by Lewdninja** [comment]
It can't find ffmpeg. You can manually specify its path under Settings.
