### ISSUE TITLE
TLDR: Relaunching the app is necessary before backing up your data to get the proper, latest bookmarks when updating versions

### ISSUE THREAD

**Issue by ddpk** [Lewdninja/liveme-pro-tools#76]
I originally was going to post about how the app doesn't backup the latest data properly. But just found out you have to relaunch the app first before backing up. If you try backing up while you've had the app open for a few days, then restore with that backup file, it will roll you back to the bookmarks and data you had the day you last opened the app. This is basically just a reminder for anyone who's updating to newer releases if there's no workaround to "fixing" the need to relaunch before backing up. 

Wrong way:
1. Backup
2. Close app
3. Install new version
4. Restore backup

Proper way:
1. **Relaunch app**
2. Backup
3. Close app
4. Install new version
5. Restore backup

If you do it the "wrong way" and you've had the app open for maybe a week straight, which i'm assuming a lot of people do... every bookmark you saved during that week is lost

I'm unsure how the auto transferring of bookmarks works but I'm guessing you would have to first relaunch the app for that, too? When I updated from 1.1.6-alpha.1 to 1.1.8, I first tried to rely on bookmarks and data switching over to the new install on its own to see if it works, and it rolled me back a few days on the bookmarks I had. Maybe because I didn't reopen 1.1.6-alpha.1 first before installing 1.1.8. But then when I went to restore with my **liveme-pro-tools-backup,tar** file, nothing changed, it was the same bookmarks that automatically transferred. I must have done it the "wrong way"

I think many people could easily make this mistake too when they see a new version comes out. Say they close the app, download the .exe and install it. You'd think they have no reason to reopen the old version first because they're closing it to never use again and switching to a newer version.  

Found this using Windows 10 and the .exe installers only.

**Comment by Xqqz** [comment]
Thanks for the info @ddpk

**Comment by simonwood1** [comment]
@Lewdninja I tried this process and restored only to end up losing all my bookmarks. The RAR file was created, but all four JSON files contained only "[]" :(

**Comment by ddpk** [comment]
@simonwood1 Well the original data files are saved here C:\Users\NAME\AppData\Roaming\liveme-pro-tools So there's no way anything I said here caused them to delete. I don't know what could have caused them not to automatically transfer over to your new version but I guess I should have advised to double check the backup files to see if your latest bookmarked user is at the bottom of the text. This is just a backup anyway. You shouldn't even need it, it's just nice to have to be safe
