### ISSUE TITLE
help

### ISSUE THREAD

**Issue by alex1311alex** [Lewdninja/liveme-pro-tools#77]
i am new to liveme pro tool i cant seem to get the replay to come up it keeps saying (error you are not authenticated please enter your login details under setting) i have it filled out but i still get the same error

**Comment by ddpk** [comment]
Look through this to see if you messed up somewhere https://github.com/Lewdninja/liveme-pro-tools/issues/37#issuecomment-385051555

**Comment by venghye** [comment]
Are you on a Mac? That bug has been happening with all Mac versions of the app since 5 days ago no matter what is done, no idea why. The dev already said OSX versions are not being supported going forward, so I guess our best bet at this point is to give up & try the windows version if possible :'(

**Comment by alex1311alex** [comment]
i am using windows i when through the steps on #37 but it keeps saying wrong verify code even when it is typed in right

**Comment by Xqqz** [comment]
@alex1311alex  register a new Gmail account on live.me , then use that to log-in on LMPT , 
problem fixed in 5 minutes, instead of waiting here hours for a solution.

**Comment by alex1311alex** [comment]
i got it working thanks for the help
