### ISSUE TITLE
Lewdninja

### ISSUE THREAD

**Issue by macuser1000** [Lewdninja/liveme-pro-tools#78]
We are all grateful that you decided to take over the compiling of Live Pro tool but then you decide to dump the mac part, You can't do that. You take over it all, Just because we mac users don't use shitty windows we get punished because you are too lazy to work out the kinks on the Mac side. You say you don't have Mac how about you install a VM and get one. Jesus it doesn't seem that hard, You are supposed to be a developer correct, well how about you take up the challenge and stop your fucking whinging that it is too hard.

**Comment by Lewdninja** [comment]
Hello @macuser1000 

Kindly take a look at **this response** from the actual author who made this script, here: https://github.com/thecoder75/liveme-pro-tools/issues/13

How about you install a VM on your glorious MAC machine and install shitty Windows on it where this tool actually works on? Jesus, it doesn't seem that hard. Stop fucking whinging.

**Comment by smagdan** [comment]
Who the fuck are you to talk to him like that, asshole.
