### ISSUE TITLE
Replay comments history is broken

### ISSUE THREAD

**Issue by smagdan** [Lewdninja/liveme-pro-tools#8]
The comments history button on replays opens up a blank window that never loads. This issue happened after the new auth requirements. Also sidenote the comments had an ugly blue design when it was working and inability to expand the window lengthwise (nitpicks).

**Comment by ddpk** [comment]
What use does comment history even have? Should it not just be removed?

**Comment by dasheron** [comment]
@ddpk You can find usefull information in the history! just saying, lol

**Comment by smagdan** [comment]
It shows all the time-stamped comments made during a stream.. it’s not useless.

**Comment by ddpk** [comment]
I mean, I know what it does I just can't think of any examples where a viewers comment would be useful. Unless you really like stalking then by all means...

**Comment by smagdan** [comment]
I pointed out a couple changes in the code for the other part of the issue.. not sure if you can see them or not. Just suggestions. Think it was page_comments.css and index.js
