### ISSUE TITLE
Fans & Following buttons on search results open wrong page

### ISSUE THREAD

**Issue by barakaka** [Lewdninja/liveme-pro-tools#80]
Search for a username, say "bob", and click on the fans and followings buttons on all the results and it opens the fans/followings for whatever user you last visited, not the one in the search result.

**Comment by tp9ine** [comment]
Yeah i've noticed this for a long time. Not that big of an issue.  You just have to click on "replays" first and then get to their fans/following from there.

**Comment by Lewdninja** [comment]
Should be fixed in 1.1.9
