### ISSUE TITLE
Account no longer available

### ISSUE THREAD

**Issue by starsaillor** [Lewdninja/liveme-pro-tools#83]
Since this morning, any user profile I try check returns the same response, "account no longer available". 

Another issue is that followers/following lists are showing no data. 

It might be just another bug on their servers, but I decided to keep you guys in the loop just in case someone else is experiencing this behaviour.

**Comment by Johnlourence** [comment]
I have the same issues my friend. Hopefully just a bug on their servers.

**Comment by starsaillor** [comment]
most likely it is. lets wait a while;

**Comment by TuxNuX** [comment]
I have the same error
it seems that this is the same error as it was the last time
https://github.com/Lewdninja/liveme-pro-tools/issues/61

**Comment by starsaillor** [comment]
@TuxNuX the only difference being, all info on liveme website is available.

**Comment by TuxNuX** [comment]
@starsaillor exactly

**Comment by TuxNuX** [comment]
now on all accounts in my bookmark have
![screenshot_20180517_152831](https://user-images.githubusercontent.com/17123357/40180705-bba8981e-59e7-11e8-8587-3aa6f6046447.png)

I tested my login on the website, it works well

**Comment by Johnlourence** [comment]
Its all working now

**Comment by JustALostCoder** [comment]
Not working. Says the same thing on all users "Account no longer available".

**Comment by Xqqz** [comment]
5:15 AM New York Time - Not working.

**Comment by knock43** [comment]
They added a captcha it seems to browser.  Likely broke it.
https://imgur.com/a/A23bjBl

**Comment by scozz76** [comment]
Nox login working. No captcha.

**Comment by artorawley** [comment]
Tool no longer working here either. Can't search for users or bring up profiles from the bookmarks menu either.

**Comment by Lewdninja** [comment]
Captcha has nothing to do with this. This script uses their APP login method, not the SITE method.. so there's no captcha requirement.

What I've noticed is that Node `request` module fails the `appLoginCM` request which returns a empty data array while normal `curl` requests in the CLI return fine.

**Comment by stonedmonkey** [comment]
error still persists

**Comment by Lewdninja** [comment]
Fixed for Patreon supporters. Will push update and release files to Github in 24-48 hours.
https://www.patreon.com/posts/18881661

**Comment by tp9ine** [comment]
I have no methods of donating and am poor anyway. Looks like it's gonna be a long weekend :(

**Comment by Xqqz** [comment]
@tp9ine  , donations/patron is only $5 US per month , its well worth it @Lewdninja  is doing a great job at keeping up with LiveMe changes, and fixing bugs, fast.

**Comment by demondecon** [comment]
@Lewdninja I'm all for trying to make some money through additional features, or early access non-essential releases. You're also doing a great job with fixing bugs quickly. But openly admitting that an essential update is fixed but only paying supporters get access to it until a later date is a terrible look.

Don't hold be a dev that holds essential updates hostage, it's better to lock features like in app downloads to paying users, where free users only get the urls and if they want to download the file they have to find their own work around.

**Comment by barakaka** [comment]
a terrible look is getting something for free but whining because you have to wait a day for it

**Comment by Grindteeth** [comment]
If I understand correctly, I have to wait until new month before those posts unlock even if I become a patreon?

**Comment by Grindteeth** [comment]
@tp9ine ok thanks. Doesn't seem to work for me though. I've tried a few times and I get the confirmation e-mail but everything is still hidden.

**Comment by demondecon** [comment]
@barakaka I'm simply stating it's a very slippery slope.  The first critical update was for everyone immediately (Version 1.1.5), Patreon was created for extra features, immediately when a new critical update is required Patreon was changed to critical update is $5 or wait "24-48 hrs", when the dev decides the goal is to make more money the next critical update could be $5 (or an increased price) or wait a week, and so forth.  There's nothing stopping the dev from changing the terms at any time.  ANY freemium model application is for premium features not "Pay extra so that it works".   It's similar to the "You just won a free holiday" phone calls

**Comment by pope9999** [comment]
@demondecon do you remember when thecoder75 called it quits?  At that point there was no more tool.  Lewdninja stepped in and filled the void, repairing the app and breathing life back into it... year old requests like sorting were quickly added... something that thecoder just dragged his feet on...  

While i appreciate the work put in by the orig dev team ... I also greatly appreciate lewd for doing what he does albeit he is doing with some $ incentive in mind for himself...   I'm just grateful we have something that works or will be repaired if it breaks and not just abandoned... and with the added benefit that sensible requests will actually be added is the cherry on top.   I don't see anyone else stepping in to fix or tweak it.

I'm also looking forward to other requests to be presented and hopefully added... Like a possible filtering option for likes/shares from accounts pooled from "scout" accounts... last time something like that was requested thecoder75 had concerns about API bans ... but all that could easily be mitigated with throttling the requests and queries.

**Comment by barakaka** [comment]
> ANY freemium model application is for premium features not "Pay extra so that it works".

Sorry is there a freemium rulebook somewhere you're referring to?  And where did he say this was "freemium"?  

>Patreon was created for extra features

No it wasn't.  You are just mad you have to wait a day and are just grasping for reasons to justify being upset about it but all your reasons are crap.  You haven't said one negative consequence of any of his actions so far.  You just seem to allude to some vague code of conduct for programmers you think he should abide by that really just amounts to "you should code for me for free".

**Comment by pope9999** [comment]
@demondecon what I was alluding to in a round about way is... lets not try to piss off the the only guy who actually stepped up and is actively contributing to this project.    Your concern about OS compatibility is rendered moot if updates stop.

**Comment by sodoffb** [comment]
There's no problem asking for donations to keep a project going, but paywalling critical updates is a scummy move. I don't mind non critical updates or beta features being paywalled, but locking the entire application down for anyone who doesn't pay? That's not going to sit well. I'd be wary of patreon trolls arising from this.

**Comment by pope9999** [comment]
@sodoffb i'd agree with you if the paywall was permanent ... but it's not.   you are just getting a motivated coder and rewarded with early access... or on the flip side this could all be free but you'd have a less motivated coder who'd be more inclined to take his sweet time fixing it ...

**Comment by sodoffb** [comment]
Charging for this sort of program is risky business in the first place, seeing as how it can be used for illegal things. Paywalling critical features that allow access is basically charging for the program itself, which is even worse from a legal standpoint. I don't mind him charging for beta features or non critical updates, but it won't sway me on thinking that paywalling critical updates is a cheap move.

**Comment by demondecon** [comment]
@pope9999 my concern is the paywall is slowly becoming permanent.  The conversation in https://github.com/Lewdninja/liveme-pro-tools/issues/1 was 'I'll continue to update if I can get some donations to fix the scripts', then it became 'I'm not getting enough interest in donations so I'm going to consider ads', then it became 'Ads aren't going to work so premium features will be paid for', then in this thread it became critical update "Fixed for Patreon supporters. Will push update and release files to Github in 24-48 hours."  Now on the Patreon its "You'll receive early critical fixes to the app 2-3 days before anyone else."

Do you see how the slope is quickly getting steeper and trending towards paywalling, especially when Liveme appears to be actively trying to combat the issue?

@sodoffb also has some good points

**Comment by Xqqz** [comment]
How many of you guys WORK FOR FREE ?

Whining about waiting for a FREE product is ... pathetic.

**Comment by sodoffb** [comment]
No one is asking him to work for free, only to not paywall critical features on a program that borderlines illegal. 

Take a look in to the hot mess the guy who developed photofucket got in to for paywalling a downloader used for illegal activities.

**Comment by starsaillor** [comment]
I agree with the above, I wouldn't dedicate my time and effort to something like this if weren't getting any sort of compensation. I partially agree with him.

**Comment by Xqqz** [comment]
@sodoffb , WTF are you talking about with this comment "" a downloader used for illegal activities. "" ??
please tell us what "illegal activity"  you are downloading with the application. 

also, again, do you work for FREE  ?

and, I guess if Liveme.com/Live.me changes the API or any function say at 8:00 AM EST, you expect the developer here to furnish YOU with a fix at 8:01 AM EST , right ?  and for FREE. 

to use YOUR OWN words ""You can see where this is going""

**Comment by robwas** [comment]
I'm just happy someone is continuing to update the program...  sad to see angry comments because you have to wait a few days, often that's the case anyways when it comes to fixes and dedicating free time to a project like this.  A big thank you to Lewdninja for keeping this going, it's a great tool.

**Comment by Lewdninja** [comment]
I'll make a full response to this discussion soon once I've gathered my thoughts.

**Comment by ddpk** [comment]
Damn, this is too much to read I won't bother. 

Before there was any incentive to become a patron, he literally only had 3. This gets people helping out, because they should. It can be a group effort too, meaning the more patrons he gets the more we can get with the tool through higher patron goals or other things he comes up with while individually we're all still contributing the same fair amount per month. Why in the world would he want to spend time on this for free though? Because the original dev did? Fuck that, Thecoder75 should have done Patreon too. It's literally a tool you probably use for getting free jerkoff material. The fact that you're complaining about going a few days without it is pretty pathetic and unhealthy. People ask way too much from someone that just hands everything to them for free and when it comes time to pay them back for it, you shouldn't be surprised or get upset

By the way @Lewdninja, you'll really buy a Mac? That was funny to see after reading this [cry baby's](https://github.com/Lewdninja/liveme-pro-tools/issues/78) complaint. I don't know why people expect an program like this to magically work on all OS's

**Comment by Lewdninja** [comment]
@ddpk Yes.

**Comment by TuxNuX** [comment]
@Lewdninja 

instead of buying computer with mac os it would not be enough to use "virtual box"

http://www.wikigain.com/install-macos-sierra-10-12-virtualbox/

**Comment by TuxNuX** [comment]
many people here really have the s.... mentality of "Windows"
stop screaming after @Lewdninja 
if you are not happy download "source" apply your fix and compile
