### ISSUE TITLE
Bookmarks Eye not working ?

### ISSUE THREAD

**Issue by thegeezer9999** [Lewdninja/liveme-pro-tools#85]
Home page, shows say three new replays since last visit. Open bookmarks, hit the eye, shows no new replays. Think this is pretty key functionality ?

**Comment by Xqqz** [comment]
Hitting the EYE too fast will show no results ( LMPT has not yet found a "following" with new replays - still scanning ) 

I wait 1 to 2 minutes ( depends on how many bookmarks you have )  for the LMPT to finish scanning the whole bookmarks list, then hit the eye and all results ( if any with NEW REPLAYS ) will show with a green background.
