### ISSUE TITLE
nothings work

### ISSUE THREAD

**Issue by bubu23bubu23** [Lewdninja/liveme-pro-tools#86]
try the app and sudenlly nothings work , it happened to you too?

**Comment by scozz76** [comment]
Discussion is here #83

**Comment by bubu23bubu23** [comment]
no my friend that was yersterday and it fixed it was server problem but in the past 3 houres nothing work no replay show or somthing nothing work i think its new 
my app worked untill 3 houres ago

**Comment by scozz76** [comment]
The issue appears to include the one you raised
