### ISSUE TITLE
Search bar not working

### ISSUE THREAD

**Issue by Gaminguseonly** [Lewdninja/liveme-pro-tools#87]
I've tried typing the username, the user short id, any of the options and it just constantly says Performing LiveMe Search.... and doesn't do anything else. Tried it with other users as well. It was working fine yesterday and the only thing I've done since was add in bookmarks and watch some replys. Today, it stopped working.

**Comment by Gaminguseonly** [comment]
I do have the latest version 1.1.8.

**Comment by demondecon** [comment]
@Gaminguseonly  @tp9ine is talking about 1.1.9 which is only available right now if you pay @lewdninja $5 a month as a Patreon subscriber

**Comment by Lewdninja** [comment]
https://github.com/Lewdninja/liveme-pro-tools/issues/83
