### ISSUE TITLE
IP banned from liveme?

### ISSUE THREAD

**Issue by m4gnet98** [Lewdninja/liveme-pro-tools#90]
Hi. No idea where else to write this.

Anyone else still having problems with "Account no longer available"?
I also can't load any streams on their webpage.
Neither log into my account on my phone via wifi.

It DOES work with VPN active on their webpage.

Only thing I have done is using the program from @Lewdninja (not blaming you)

Thanks

**Comment by tp9ine** [comment]
newest version? 1.1.9?

**Comment by m4gnet98** [comment]
Using newest version, yes. 1.1.9 that is.

**Comment by tp9ine** [comment]
Oh. Well I had that problem before a couple weeks ago but not with the 'account not available' message. My experience was that replays simply didn't show up - however, logging in to another account in the settings made the replays show again. And logged back in to the initial account later made it work again. So yeah perhaps try another account for a sec.

**Comment by ddpk** [comment]
You shouldn't use a main account if you care about it, just in case. Make a throwaway account, takes 2 minutes. It shouldn't matter to you if it's your main account or a throwaway you login with since it's just used for gaining auth access and everything is local on Liveme Pro Tools. I don't think Liveme would ban accounts using this and I highly doubt they IP ban. Could be your internet. Let everyone know if you fixed it or it fixed itself so no one has to guess! If browser still doesn't work i'd try clearing browser data (Cookies, cache)

**Comment by m4gnet98** [comment]
Thanks for taking your time to reply

Idk what it could be, but it's something on my end for sure though.
Different browsers doesn't work (not even in "inkognito mode")
On phone doesn't work either (although I only have access to wifi on it, no mobile data)
It works with VPN. So either my ISP blocks something, or I'm half-ip-banned or something wierd. Who knows. Same account works on VPN.

I have a throwaway account on Liveme Pro Tools.


Anyway I won't write any more here unless it gets fixed.

**Comment by ddpk** [comment]
Have you tried rebooting your router yet? If you have Windows 10 you can try [Mobile Hotspot](https://www.pcworld.com/article/3194707/windows/how-to-use-your-windows-10-pc-as-a-mobile-hotspot.html) as a test? But I couldn't really tell ya what it would mean if the Hotspot did or didn't work so...

**Comment by knock43** [comment]
Yes it's possible to get IP banned.  It happened to me when I was using my own script which messed up and kept making requests every second while I was away/sleeping.  A simple modem restart fixes this assuming you don't have a static IP.  It's a crazy amount of requests to get IP banned, though.  I'm surprised this happened to you..  Were you going too ham?

**Comment by knock43** [comment]
It's also a form of ddos protection..  Though would be very hard if not impossible to saturate with requests of ~10-20kb

**Comment by m4gnet98** [comment]
Does not work after router reboot.

I didn't so called "go ham", I was using 1.1.8 until it stopped working, then while I was waiting for 1.1.9 this happened.

Oh well 
Thank you none the less guys.

**Comment by ddpk** [comment]
I doubt it was any kind of ban then unless like knock43 said, you have a static IP making the reboot do nothing. For sure, at least, you know your accounts weren't banned. Could be your ISP
