### ISSUE TITLE
Add a column for replay id visible somewhere

### ISSUE THREAD

**Issue by tp9ine** [Lewdninja/liveme-pro-tools#91]
It really makes it quick and easy to identify a replay and comparing it against a download, like when you want to go back later and check the comments of a particular vid or something else. 

It is especially helpful after a crash (because blue icon is shown for a partial/crashed DL). 

Perhaps an option to enable because it might be clutter to some, but the helpfulness really outweighs it, imo.

I became a patreon yesterday and would really appreciate it.  :)

**Comment by ddpk** [comment]
Having the visible ID also made it easier going through a large replay list when you're downloading/viewing one by one, it really helped me not lose my place

**Comment by tp9ine** [comment]
@ddpk Yes, exactly like the old LMT. I thought about the hovering idea, but it would be tedious and time consuming having to wait for it, if it appears in same manner as a tooltip (with a delay). Otherwise, if it appears instantly on-hover, I guess I could settle for that, as long as it's programmed in a manner that the mouse cursor will not get in the way of the numbers.

**Comment by ddpk** [comment]
@tp9ine True, never thought about that. I wish there could be room for it to be the old way where it's visible but I'm sure that's just a little too much work to bother.
