### ISSUE TITLE
Chunk Download Error

### ISSUE THREAD

**Issue by GumiG** [Lewdninja/liveme-pro-tools#93]
so i had no problems on the old version(6.3.3ish) with this method. now the chunks are still downloading but when its finished they dont fuse together and i get a "Download Error". 
any solution?

**Comment by thegeezer9999** [comment]
Use FFMPEG - works 99.99% of time

**Comment by TuxNuX** [comment]
I use chunk + contat and always good work
only problem the file size is much bigger than with ffmpeg

**Comment by GumiG** [comment]
i used ffmpeg on the old version but it doesnt seem to work now.. i just keep on using the chunk method and fuse them myself.

**Comment by simonwood1** [comment]
I agree, now that we have parallel downloads (thanks @Lewdninja !), the FFMPEG seems to be a more reliable method. Like chunk+concat method however, there are still streams that inevitably lock up and therefore choke the queue - when this happens to me, I simply increase the number of simultaneous downloads to resume other broadcasts 'stuck' in the queue
