### ISSUE TITLE
Other feature suggestion: Screenlist as seen on OpenPeriscope

### ISSUE THREAD

**Issue by ricabartoli** [Lewdninja/liveme-pro-tools#95]
First of all many thanks to @Lewdninja for mantaining this great liveme-pro-tools. I thinking about the best way to avoiding playing a replay to look for interesting frames before donwloading the video. 

Would be possible to include a "Screenlist" feature as seen on OpenPeriscope?

Go to:
[https://github.com/Pmmlabs/OpenPeriscope](url)

Such tool extracts video frames as an index in a very short time so is not necessary to play the replay to see its contain.

(Sorry for my english)
Best regards

**Comment by Lewdninja** [comment]
Not possible with the current API as far as I know.
