### ISSUE TITLE
Feature request: Search results should be in a pop-up/new-window

### ISSUE THREAD

**Issue by Xqqz** [Lewdninja/liveme-pro-tools#96]
I think it would be a good idea to have search results open in a new window/pop-up.

When you do a #HASHTAG or USERNAME LIKE search, and you get the result, click on one of the accounts.....

in order to get that SEARCH "result" BACK , one has to do a complete NEW SEARCH with the HASHTAG/USERNAME LIKE again.....

Wish the search-result opened-and-stay in a window the way bookmarks/followers/followings do.

Unless there's a "BACK" button to take us BACK to the LAST SEARCH RESULT.

Community members, is this a good idea, or not ?

**Comment by thegeezer9999** [comment]
Great idea

Even better if you could then filter out those with zero replays

**Comment by Xqqz** [comment]
@TuxNuX  , the "New Replays Window" is already there, just have to give it time to load

![bandicam 2018-05-25 08-55-25-679](https://user-images.githubusercontent.com/38635388/40545483-825af8d8-601b-11e8-91b6-4dbd18340452.jpg)

# if that's what you meant.

**Comment by TuxNuX** [comment]
ohhh thank you @Xqqz 
I did not know because the "bubble info" does not work in the bookmark pop-up
