### ISSUE TITLE
[Solved] How to get FFMPEG to download, correct path

### ISSUE THREAD

**Issue by Xqqz** [Lewdninja/liveme-pro-tools#97]
My Environment Variables

 c:\ffmpeg\bin;C:\AppServ\Apache24\bin;C:\AppServ\php5;C:\AppServ\MySQL\bin

...................ERROR LOG from LMPT....................................
[
  {
    "code": "ENOENT",
    "errno": "ENOENT",
    "syscall": "spawn C:\\ffmpeg\\bin",
    "path": "C:\\ffmpeg\\bin",
    "spawnargs": [
      "-formats"
    ]
  },
  null,
  null
]
....................END of ERROR LOG .................................

My FFMPEG PATH : c:\ffmpeg\bin

On 1.1.7 it was working fine, with that path, it's not working now on LMPT 1.1.9 

putting FFMPEG in c:\windows\ffmpeg\bin does NOT fix/work

Anyone else have this problem ?

I notice, after restarting LMPT.. the FFMPEG path is no longer shown/saved in the LMPT SETTINGS. ( under FFMPEG LOCATION )

* yes i do have 2 download managers that works perfectly

**Comment by scozz76** [comment]
My ffmpeg is located at "c:\Windows\ffmpeg\bin" with the enviroment variables for <user> (path) set to the same.
No problems.
If you enter the path in LMPT, I pretty sure you have to add "ffmpeg.exe". In my case that would be C:\Windows\ffmpeg\bin\ffmpeg.exe

**Comment by Xqqz** [comment]
@scozz76  , thank you for the tip,  adding the "ffmpeg.exe" seems to have fixed the issue. Downloads works now.

# C:\ffmpeg\bin\ffmpeg.exe  . 

That is working for me
